// --------------------------------------------------------------------------------------------------------------------
// <copyright file="InternalMovements.cs" company="Microsoft">
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
//    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
//    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
//    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//    OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>

namespace Ecp.True.Bdd.Tests.Entities
{
    using System.Xml.Serialization;

    /// <remarks/>
    [System.SerializableAttribute()]
    [XmlRoot("INTERNALMOVEMENTS")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class InternalMovements
    {
        private System.DateTime dateField;

        private string systemField;

        private INTERNALMOVEMENTSINTERNALMOVEMENT internalMovementField;

        /// <remarks/>
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        public string System
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }

        /// <remarks/>
        public INTERNALMOVEMENTSINTERNALMOVEMENT INTERNALMOVEMENT
        {
            get
            {
                return this.internalMovementField;
            }
            set
            {
                this.internalMovementField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENT
    {
        private ulong movementIdField;

        private string movementTypeField;

        private string movementCommodityField;

        private string movementCommodityTypeField;

        private INTERNALMOVEMENTSINTERNALMOVEMENTOWNERS ownersField;

        private INTERNALMOVEMENTSINTERNALMOVEMENTBATCHES batchesField;

        private INTERNALMOVEMENTSINTERNALMOVEMENTPERIOD periodField;

        private string caseField;

        private INTERNALMOVEMENTSINTERNALMOVEMENTLOCATION locationField;

        private INTERNALMOVEMENTSINTERNALMOVEMENTCRITERION[] criteriaField;

        private string actionField;

        /// <remarks/>
        public ulong MOVEMENTID
        {
            get
            {
                return this.movementIdField;
            }
            set
            {
                this.movementIdField = value;
            }
        }

        /// <remarks/>
        public string MOVEMENTTYPE
        {
            get
            {
                return this.movementTypeField;
            }
            set
            {
                this.movementTypeField = value;
            }
        }

        /// <remarks/>
        public string MOVEMENTCOMMODITY
        {
            get
            {
                return this.movementCommodityField;
            }
            set
            {
                this.movementCommodityField = value;
            }
        }

        /// <remarks/>
        public string MOVEMENTCOMMODITYTYPE
        {
            get
            {
                return this.movementCommodityTypeField;
            }
            set
            {
                this.movementCommodityTypeField = value;
            }
        }

        /// <remarks/>
        public INTERNALMOVEMENTSINTERNALMOVEMENTOWNERS OWNERS
        {
            get
            {
                return this.ownersField;
            }
            set
            {
                this.ownersField = value;
            }
        }

        /// <remarks/>
        public INTERNALMOVEMENTSINTERNALMOVEMENTBATCHES BATCHES
        {
            get
            {
                return this.batchesField;
            }
            set
            {
                this.batchesField = value;
            }
        }

        /// <remarks/>
        public INTERNALMOVEMENTSINTERNALMOVEMENTPERIOD PERIOD
        {
            get
            {
                return this.periodField;
            }
            set
            {
                this.periodField = value;
            }
        }

        /// <remarks/>
        public string CASE
        {
            get
            {
                return this.caseField;
            }
            set
            {
                this.caseField = value;
            }
        }

        /// <remarks/>
        public INTERNALMOVEMENTSINTERNALMOVEMENTLOCATION LOCATION
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("CRITERION", IsNullable = false)]
        public INTERNALMOVEMENTSINTERNALMOVEMENTCRITERION[] CRITERIA
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ACTION
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENTOWNERS
    {
        private INTERNALMOVEMENTSINTERNALMOVEMENTOWNERSOWNER ownerField;

        /// <remarks/>
        public INTERNALMOVEMENTSINTERNALMOVEMENTOWNERSOWNER OWNER
        {
            get
            {
                return this.ownerField;
            }
            set
            {
                this.ownerField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENTOWNERSOWNER
    {
        private string ownerIdField;

        private string ownerTypeField;

        private INTERNALMOVEMENTSINTERNALMOVEMENTOWNERSOWNERQUANTITY quantityField;

        /// <remarks/>
        public string OWNERID
        {
            get
            {
                return this.ownerIdField;
            }
            set
            {
                this.ownerIdField = value;
            }
        }

        /// <remarks/>
        public string OWNERTYPE
        {
            get
            {
                return this.ownerTypeField;
            }
            set
            {
                this.ownerTypeField = value;
            }
        }

        /// <remarks/>
        public INTERNALMOVEMENTSINTERNALMOVEMENTOWNERSOWNERQUANTITY QUANTITY
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENTOWNERSOWNERQUANTITY
    {
        private byte valueField;

        private string uomField;

        private string pROPERTYField;

        /// <remarks/>
        public byte VALUE
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string UOM
        {
            get
            {
                return this.uomField;
            }
            set
            {
                this.uomField = value;
            }
        }

        /// <remarks/>
        public string PROPERTY
        {
            get
            {
                return this.pROPERTYField;
            }
            set
            {
                this.pROPERTYField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENTBATCHES
    {
        private INTERNALMOVEMENTSINTERNALMOVEMENTBATCHESBATCH batchField;

        /// <remarks/>
        public INTERNALMOVEMENTSINTERNALMOVEMENTBATCHESBATCH BATCH
        {
            get
            {
                return this.batchField;
            }
            set
            {
                this.batchField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENTBATCHESBATCH
    {
        private byte batchIdField;

        private string commodityNameField;

        private string commodityTypeField;

        /// <remarks/>
        public byte BATCHID
        {
            get
            {
                return this.batchIdField;
            }
            set
            {
                this.batchIdField = value;
            }
        }

        /// <remarks/>
        public string COMMODITYNAME
        {
            get
            {
                return this.commodityNameField;
            }
            set
            {
                this.commodityNameField = value;
            }
        }

        /// <remarks/>
        public string COMMODITYTYPE
        {
            get
            {
                return this.commodityTypeField;
            }
            set
            {
                this.commodityTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENTPERIOD
    {
        private System.DateTime sTARTTIMEField;

        private System.DateTime eNDTIMEField;

        /// <remarks/>
        public System.DateTime STARTTIME
        {
            get
            {
                return this.sTARTTIMEField;
            }
            set
            {
                this.sTARTTIMEField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ENDTIME
        {
            get
            {
                return this.eNDTIMEField;
            }
            set
            {
                this.eNDTIMEField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENTLOCATION
    {
        private string sOURCEField;

        private string sOURCETYPEField;

        private string dESTINATIONField;

        private string dESTINATIONTYPEField;

        /// <remarks/>
        public string SOURCE
        {
            get
            {
                return this.sOURCEField;
            }
            set
            {
                this.sOURCEField = value;
            }
        }

        /// <remarks/>
        public string SOURCETYPE
        {
            get
            {
                return this.sOURCETYPEField;
            }
            set
            {
                this.sOURCETYPEField = value;
            }
        }

        /// <remarks/>
        public string DESTINATION
        {
            get
            {
                return this.dESTINATIONField;
            }
            set
            {
                this.dESTINATIONField = value;
            }
        }

        /// <remarks/>
        public string DESTINATIONTYPE
        {
            get
            {
                return this.dESTINATIONTYPEField;
            }
            set
            {
                this.dESTINATIONTYPEField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INTERNALMOVEMENTSINTERNALMOVEMENTCRITERION
    {
        private string[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DESCRIPTION", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PROPERTY", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("UOM", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("VALUE", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("VALUETYPE", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public string[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        DESCRIPTION,

        /// <remarks/>
        PROPERTY,

        /// <remarks/>
        UOM,

        /// <remarks/>
        VALUE,

        /// <remarks/>
        VALUETYPE,
    }
}
