// --------------------------------------------------------------------------------------------------------------------
// <copyright file="Inventory.cs" company="Microsoft">
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
//    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
//    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
//    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//    OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>

namespace Ecp.True.Bdd.Tests.Entities
{
    // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class INVENTORIES
    {

        private System.DateTime dATEField;

        private string sYSTEMField;

        private INVENTORIESINVENTORY iNVENTORYField;

        /// <remarks/>
        public System.DateTime DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }

        /// <remarks/>
        public string SYSTEM
        {
            get
            {
                return this.sYSTEMField;
            }
            set
            {
                this.sYSTEMField = value;
            }
        }

        /// <remarks/>
        public INVENTORIESINVENTORY INVENTORY
        {
            get
            {
                return this.iNVENTORYField;
            }
            set
            {
                this.iNVENTORYField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INVENTORIESINVENTORY
    {

        private string lOCATIONIDField;

        private string lOCATIONTYPEField;

        private string cASEField;

        private System.DateTime dATEField;

        private INVENTORIESINVENTORYCOMMODITY[] cOMMODITIESField;

        private string aCTIONField;

        /// <remarks/>
        public string LOCATIONID
        {
            get
            {
                return this.lOCATIONIDField;
            }
            set
            {
                this.lOCATIONIDField = value;
            }
        }

        /// <remarks/>
        public string LOCATIONTYPE
        {
            get
            {
                return this.lOCATIONTYPEField;
            }
            set
            {
                this.lOCATIONTYPEField = value;
            }
        }

        /// <remarks/>
        public string CASE
        {
            get
            {
                return this.cASEField;
            }
            set
            {
                this.cASEField = value;
            }
        }

        /// <remarks/>
        public System.DateTime DATE
        {
            get
            {
                return this.dATEField;
            }
            set
            {
                this.dATEField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("COMMODITY", IsNullable = false)]
        public INVENTORIESINVENTORYCOMMODITY[] COMMODITIES
        {
            get
            {
                return this.cOMMODITIESField;
            }
            set
            {
                this.cOMMODITIESField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ACTION
        {
            get
            {
                return this.aCTIONField;
            }
            set
            {
                this.aCTIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INVENTORIESINVENTORYCOMMODITY
    {

        private string cOMMODITYNAMEField;

        private string cOMMODITYTYPEField;

        private string bATCHIDField;

        private byte oRDENField;

        private INVENTORIESINVENTORYCOMMODITYCRITERIA cRITERIAField;

        private INVENTORIESINVENTORYCOMMODITYOWNERS oWNERSField;

        /// <remarks/>
        public string COMMODITYNAME
        {
            get
            {
                return this.cOMMODITYNAMEField;
            }
            set
            {
                this.cOMMODITYNAMEField = value;
            }
        }

        /// <remarks/>
        public string COMMODITYTYPE
        {
            get
            {
                return this.cOMMODITYTYPEField;
            }
            set
            {
                this.cOMMODITYTYPEField = value;
            }
        }

        /// <remarks/>
        public string BATCHID
        {
            get
            {
                return this.bATCHIDField;
            }
            set
            {
                this.bATCHIDField = value;
            }
        }

        /// <remarks/>
        public byte ORDEN
        {
            get
            {
                return this.oRDENField;
            }
            set
            {
                this.oRDENField = value;
            }
        }

        /// <remarks/>
        public INVENTORIESINVENTORYCOMMODITYCRITERIA CRITERIA
        {
            get
            {
                return this.cRITERIAField;
            }
            set
            {
                this.cRITERIAField = value;
            }
        }

        /// <remarks/>
        public INVENTORIESINVENTORYCOMMODITYOWNERS OWNERS
        {
            get
            {
                return this.oWNERSField;
            }
            set
            {
                this.oWNERSField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INVENTORIESINVENTORYCOMMODITYCRITERIA
    {

        private INVENTORIESINVENTORYCOMMODITYCRITERIACRITERION cRITERIONField;

        /// <remarks/>
        public INVENTORIESINVENTORYCOMMODITYCRITERIACRITERION CRITERION
        {
            get
            {
                return this.cRITERIONField;
            }
            set
            {
                this.cRITERIONField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INVENTORIESINVENTORYCOMMODITYCRITERIACRITERION
    {

        private uint vALUEField;

        private string uOMField;

        private string pROPERTYField;

        /// <remarks/>
        public uint VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }

        /// <remarks/>
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        public string PROPERTY
        {
            get
            {
                return this.pROPERTYField;
            }
            set
            {
                this.pROPERTYField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INVENTORIESINVENTORYCOMMODITYOWNERS
    {

        private INVENTORIESINVENTORYCOMMODITYOWNERSOWNER oWNERField;

        /// <remarks/>
        public INVENTORIESINVENTORYCOMMODITYOWNERSOWNER OWNER
        {
            get
            {
                return this.oWNERField;
            }
            set
            {
                this.oWNERField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INVENTORIESINVENTORYCOMMODITYOWNERSOWNER
    {

        private string oWNERIDField;

        private string oWNERTYPEField;

        private INVENTORIESINVENTORYCOMMODITYOWNERSOWNERQUANTITY qUANTITYField;

        /// <remarks/>
        public string OWNERID
        {
            get
            {
                return this.oWNERIDField;
            }
            set
            {
                this.oWNERIDField = value;
            }
        }

        /// <remarks/>
        public string OWNERTYPE
        {
            get
            {
                return this.oWNERTYPEField;
            }
            set
            {
                this.oWNERTYPEField = value;
            }
        }

        /// <remarks/>
        public INVENTORIESINVENTORYCOMMODITYOWNERSOWNERQUANTITY QUANTITY
        {
            get
            {
                return this.qUANTITYField;
            }
            set
            {
                this.qUANTITYField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class INVENTORIESINVENTORYCOMMODITYOWNERSOWNERQUANTITY
    {

        private byte vALUEField;

        private string uOMField;

        private string pROPERTYField;

        /// <remarks/>
        public byte VALUE
        {
            get
            {
                return this.vALUEField;
            }
            set
            {
                this.vALUEField = value;
            }
        }

        /// <remarks/>
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        public string PROPERTY
        {
            get
            {
                return this.pROPERTYField;
            }
            set
            {
                this.pROPERTYField = value;
            }
        }
    }


}
