// --------------------------------------------------------------------------------------------------------------------
// <copyright file="InventoryJson.cs" company="Microsoft">
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
//    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
//    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
//    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//    OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>

namespace Ecp.True.Bdd.Tests.Entities
{
    using System;

    public class InventoryJson
    {
        public string SourceSystem { get; set; }

        public string DestinationSystem { get; set; }

        public string EventType { get; set; }

        public int InventoryId { get; set; }

        public DateTime InventoryDate { get; set; }

        public string NodeId { get; set; }

        public string Observations { get; set; }

        public string Scenario { get; set; }

        public Product[] Products { get; set; }
    }

    public class Product
    {
        public string ProductId { get; set; }

        public string ProductType { get; set; }

        public int ProductVolume { get; set; }

        public string MeasurementUnit { get; set; }

        public owner[] Owners { get; set; }

        public Attribute[] Attributes { get; set; }
    }

    public class owner
    {
        public int OwnerId { get; set; }

        public int OwnershipValue { get; set; }

        public string OwnershipValueUnit { get; set; }
    }

    public class attribute
    {
        public string AttributeId { get; set; }

        public int AttributeValue { get; set; }

        public string ValueAttributeUnit { get; set; }

        public object AttributeDescription { get; set; }
    }

}
