// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MovementJson.cs" company="Microsoft">
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
//    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
//    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
//    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//    OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>

namespace Ecp.True.Bdd.Tests.Entities1
{
    using System;

    public class MovementJson
    {
        public string SourceSystem { get; set; }
        public string EventType { get; set; }
        public string MovementId { get; set; }
        public string MovementTypeId { get; set; }
        public DateTime OperationalDate { get; set; }
        public object GrossStandardVolume { get; set; }
        public string NetStandardVolume { get; set; }
        public string MeasurementUnit { get; set; }
        public string Scenario { get; set; }
        public object Observations { get; set; }
        public string Classification { get; set; }
        public Attribute[] Attributes { get; set; }
        public Owner[] Owners { get; set; }
        public Period Period { get; set; }
        public Movementsource MovementSource { get; set; }
        public Movementdestination MovementDestination { get; set; }
    }

    public class Period
    {
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
    }

    public class Movementsource
    {
        public string SourceNodeId { get; set; }
        public object SourceStorageLocationId { get; set; }
        public string SourceProductId { get; set; }
        public string SourceProductTypeId { get; set; }
    }

    public class Movementdestination
    {
        public string DestinationNodeId { get; set; }
        public object DestinationStorageLocationId { get; set; }
        public object DestinationProductId { get; set; }
        public object DestinationProductTypeId { get; set; }
    }

    public class Attribute
    {
        public string AttributeId { get; set; }
        public string AttributeValue { get; set; }
        public string ValueAttributeUnit { get; set; }
        public string AttributeDescription { get; set; }
    }

    public class Owner
    {
        public string OwnerId { get; set; }
        public string OwnershipValue { get; set; }
        public string OwnershipValueUnit { get; set; }
    }
}
