// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UIContent.cs" company="Microsoft">
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
//    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
//    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
//    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//    OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

namespace Ecp.True.Bdd.Tests.Entities
{
    using System;
    using System.Collections.Generic;

    public static class UIContent
    {
        public static Dictionary<string, string> Conversion { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Category", "Categoría" },
            { "Category Elements", "Elementos de categorías" },
            { "Create Category", "Crear categoría" },
            { "Edit Category", "Editar categoría" },
            { "Element", "Elemento" },
            { "Create Element", "Crear elemento" },
            { "Edit Element", "Editar elemento" },
            { "Grouping Categories", "Configuración para agrupar nodos" },
            { "NodeConnectionId", "NodeConnectionId" },
            { "Edit Property Information", "Editar Información Propiedad" },
            { "DummyId", "0" },
            { "DummyName", "AAAA" },
            { "ConfigureAttributesConnections", "Configuración de atributos conexiones" },
            { "ConfigureAttributesNodes", "Configuración de atributos nodos" },
            { "FileUpload", "Cargue de movimientos e inventarios" },
            { "Insert", "Insertar" },
            { "Update", "Actualizar" },
            { "Delete", "Eliminar" },
            { "Active", "Activo" },
            { "Inactive", "Inactivo" },
            { "Yes", "Sí" },
            { "Edit Property Functions", "Editar Funciones de Propiedad" },
            { "il_Rule", "PI - Por Entradas" },
            { "ul_Rule", "PNI - Por Disponible" },
            { "to_Rule", "TO - Por Inventario Inicial" },
            { "if_Rule", "IF - Por Disponible Mensual" },
            { "il_Rule1", "PI - Por Salidas" },
            { "ul_Rule1", "PNI - Por Inventario Inicial" },
            { "to_Rule1", "TO - Por Disponible" },
            { "if_Rule1", "IF - Por Entradas" },
            { "Identified LossesRule", "il" },
            { "UnIdentified LossesRule", "ul" },
            { "Outputs Tolerance Rule", "to" },
            { "Final Inventory Rule", "fi" },
            { "Ticket", "Tiquete" },
            { "TotalProcessed", "Procesados" },
            { "TotalCreated", "Creados" },
            { "Operational Cutoff", "Ejecución del corte operativo" },
            { "Note for unbalances", "Nota para desbalances" },
            { "Name", "Nombre" },
            { "Description", "Descripción" },
            { "CreatedDate", "Fecha de creación" },
            { "State", "Estado" },
            { "Segment", "Segmento" },
            { "SegmentName", "Comercial" },
            { "node-connection", "connAttributes" },
            { "node-connection-products", "connectionProducts" },
            { "node-products", "nodeProducts" },
            { "New Property Function", "Nueva Función de Propiedad" },
            { "Nodes", "Nodos" },
            { "StorageLocations", "Almacenes" },
            { "Products", "Productos" },
            { "Categories", "Categorias" },
            { "Tickets", "tickets" },
            { "CreateNodes", "Nodos" },
            { "Add Note Functions", "Nota para Mensajes con Excepción" },
            { "Add Note", "Agregar nota" },
            { "Note To Reopen", "nota para reabrir nodo aprobado" },
            { "Confirmation", "Confirmación" },
            { "01", "enero" },
            { "02", "febrero" },
            { "03", "marzo" },
            { "04", "abril" },
            { "05", "mayo" },
            { "06", "junio" },
            { "07", "julio" },
            { "08", "agosto" },
            { "09", "septiembre" },
            { "10", "octubre" },
            { "11", "noviembre" },
            { "12", "diciembre" },
            { "Jan", "ene" },
            { "Feb", "feb" },
            { "Mar", "mar" },
            { "Apr", "abr" },
            { "May", "may" },
            { "Jun", "jun" },
            { "Jul", "jul" },
            { "Aug", "ago" },
            { "Sep", "sep" },
            { "Oct", "oct" },
            { "Nov", "nov" },
            { "Dec", "dic" },
            { "CategoryLabelOnConfirmation", "1" },
            { "SegmentLabelOnConfirmation", "2" },
            { "PeriodLabel1OnConfirmation", "1" },
            { "PeriodLabel2OnConfirmation", "2" },
            { "PeriodLabel3OnConfirmation", "3" },
            { "Node", "Nodo" },
            { "Administration", "Administración" },
            { "Conveyor balance with property", "Balance de ductos y estaciones" },
            { "CreateNodeInterface", "Información general del nodo" },
            { "UpdateNodeInterface", "Información general del nodo" },
            { "Segments", "Segmento" },
            { "NodeGrid", "nodes" },
            { "Node Type", "Tipo de Nodo" },
            { "Operator", "Operador" },
            { "StorageLocationType", "Tipo de ubicación de almacénamiento" },
            { "NodeStorageLocation", "nodeStorageLocation" },
            { "ProductName", "CRUDOS IMPORTADOS" },
            { "ProductName2", "CRUDO CAMPO CEIBO" },
            { "InValidProductName", "CRUDOS IMPORTADOS" },
            { "StorageLocationProductName", "ACEITES RESIDUALES" },
            { "ProductsGrid", "products" },
            { "Logistic Center SAP", "Centro logístico SAP" },
            { "Storage Location SAP", "Almacén SAP" },
            { "see summary", "ver resumen" },
            { "see error", "ver error" },
            { "to download", "descargar" },
            { "Operational Cutoffs", "Cortes Operativos" },
            { "Execution Operational Cutoff", "Ejecución Ejecución del corte operativo" },
            { "Finalized", "Finalizado" },
            { "Processing", "Procesando" },
            { "StartDate", "Fecha Inicial" },
            { "EndDate", "Fecha Final" },
            { "ExecutionDate", "Fecha Ejecución" },
            { "Username", "Usuario" },
            { "NodeInformation", "Sin registros" },
            { "LogisticCenter", "Centro logístico SAP" },
            { "NodeTypeValue", "Refineria" },
            { "OperatorValue", "ECOPETROL" },
            { "SegmentValue", "Transporte" },
            { "LogisticCenterValue", "1000 - PR HCT" },
            { "StorageLocationSAPValue", "1000:M001 - PR HCT : MATERIA PRIMA" },
            { "Volumetric Balance with ownership", "Balance Volumétrico con propiedad" },
            { "StorageLocationValue", "1000:M001" },
            { "Ownership Rules", "Reglas de propiedad" },
            { "Ownership strategy", "Estrategia de propiedad" },
            { "Edit Property Strategy", "Editar Estrategia de Propiedad" },
            { "TransformSettings", "Configuración de transformaciones" },
            { "Movimientos", "Movements" },
            { "Inventories", "Inventarios" },
            { "FileUploadForSalesAndPurchases", "Cargue de compras, ventas y eventos PPA" },
            { "nodeAttributes", "nodeAttributes" },
            { "Balance per Node", "Balance por Nodo" },
            { "Volumetric Balance with ownership for node", "Balance operativo con propiedad por nodo" },
            { "Volumetric Balance by Node", "Balance Volumétrico por Nodo" },
            { "Status", "Estado" },
            { "Error during property calculation", "Error durante el cálculo de propiedad" },
            { "OwnershipStrategy", "Estrategia de Propiedad" },
            { "isTransfer", "Punto Transferencia" },
            { "Exceptions", "Excepciones" },
            { "Error", "Error" },
            { "OriginSystem", "Sistema origen" },
            { "Process", "Proceso" },
            { "DateCreated", "Fecha creación" },
            { "FileUploadForPlanningAndProgrammingAndCollaborationAgreements", "Cargue de compras, ventas y eventos PPA" },
            { "Planning, Programming and Agreements", "Planeación, Programación y Acuerdos" },
            { "Purchasing and Sales Contracts", "Contratos de Compras y Ventas" },
            { "Control exceptions", "Control excepciones" },
            { "SourceLocation1", "SINOPER" },
            { "DestinationLocation1", "TRUE" },
            { "GroupValue1", "Productos" },
            { "DestinationLocation2", "EXCEL" },
            { "SourceLocation2", "TRUE" },
            { "DestinationLocation3", "SINOPER" },
            { "Logistic Report Generation", "Generación reporte logístico" },
            { "Date", "Fecha" },
            { "Archive", "Archivo" },
            { "Action", "Acción" },
            { "Type", "Tipo" },
            { "Records Processed", "Registros procesados" },
            { "Owner", "Propietario" },
            { "Error generating logistic report file", "Error generando el archivo de reporte logístico" },
            { "ChangeValue", "Cambiar" },
            { "ExpireValue", "Caducar" },
            { "CategoryElement", "Facilidad" },
            { "Owners", "Propietario" },
            { "nodeAttribute", "nodeAttributes" },
            { "Sent", "Enviado a aprobación" },
            { "Publishing", "Publicando" },
            { "Ownership", "Propiedad" },
            { "Locked", "Bloqueado" },
            { "Unlocked", "Desbloqueado" },
            { "Published", "Publicado" },
            { "SubmitForApproval", "Enviado a aprobación" },
            { "Approved", "Aprobado" },
            { "Rejected", "Rechazado" },
            { "Failed", "Fallido" },
            { "Reordering the node", "Reordenamiento de Nodos" },
            { "Ownershipcalculation", "Determinación de propiedad por segmento" },
            { "Reopen", "Reabrir" },
            { "Reopened", "Reabierto" },
            { "InitialInventory", "Inventario Inicial" },
            { "FinalInventory", "Inventario Final" },
            { "Interface", "Interfase" },
            { "Contracts", "Contratos de Compras y Ventas" },
            { "nodetags", "Configurar agrupar nodos" },
            { "Edit Movement", "Editar Movimiento" },
            { "Edit Inventory", "Editar inventario final" },
            { "daily", "diaria" },
            { "weekly", "semanal" },
            { "biweekly", "quincenal" },
            { "monthly", "mensual" },
            { "Reason", "Calidad Información/Suministro Información" },
            { "Node Approval", "Aprobación de Nodos" },
            { "Graphic configuration of the network", "Configuración gráfica de la red" },
            { "Show", "Mostrar" },
            { "Flow Settings", "Configuración de flujos" },
            { "source products", "Producto Origen" },
            { "destination products", "Producto Destino" },
            { "variable", "variable" },
            { "unit", "Unidad" },
            { "movement type", "Tipo Movimiento" },
            { "reason for change", "Causal del Cambio" },
            { "Input", "Entrada" },
            { "Output", "Salida" },
            { "IdentifiedLoss​", "Pérdida Identificada" },
            { "Tolerance", "Tolerancia" },
            { "UnidentifiedLoss​", "Pérdida No Identificada" },
            { "source node", "Nodo Origen" },
            { "destination node", "Nodo Destino" },
            { "Graphic Network Configuration", "Configuración gráfica de la red" },
            { "System", "Sistema" },
            { "NewValue", "Nueva" },
            { "Balance of pipelines and stations", "Balance de ductos y estaciones" },
            { "Pipeline and station reports", "Reportes de ductos y estaciones" },
            { "Supply Chain Management", "Gestión cadena de suministro" },
            { "Load movements and inventories", "Cargue de movimientos e inventarios" },
            { "Configuration of purchases, sales and events PPA", "Configuración de compras, ventas y eventos PPA" },
            { "Predictive analytical models",  "Modelos analíticos predictivos" },
            { "Operating balance with or without property", "Balance operativo con o sin propiedad" },
            { "Control letter", "Carta de control" },
            { "Logistic movements and inventories", "Movimientos e inventarios logísticos" },
            { "Load shopping, sales and PPA events", "Cargue de compras, ventas y eventos PPA" },
            { "Execution of the operational cut", "Ejecución del Ejecución del corte operativo" },
            { "Property determination by segment", "Determinación de propiedad por segmento" },
            { "Operating balance with ownership per node", "Balance operativo con propiedad por nodo" },
            { "Approval of balance with ownership by node", "Aprobación del balance con propiedad por nodo" },
            { "Configure attributes nodes", "Configuración de atributos nodos" },
            { "Configure connections attributes", "Configuración de atributos conexiones" },
            { "Configure group nodes", "Configuración para agrupar nodos" },
            { "Homologation Configuration", "Configuración de homologaciones" },
            { "Exception Management", "Gestión de excepciones" },
            { "Configuration of transfer points - operational nodes", "Configuración de puntos transferencia - nodos operativos" },
            { "Configuration of transfer points - logistic nodes", "Configuración de puntos transferencia - nodos logísticos" },
            { "Approval Flow Settings", "Configuración de flujos de aprobación" },
            { "Change massive strategies", "Cambiar estrategias masivas" },
            { "New ownership strategy", "Nueva estrategia de propiedad" },
            { "Strategy", "Entradas" },
            { "New Strategy", "Regla Contractual" },
            { "Create Node", "Crear nodo" },
            { "Purchases Sales and Events PPA", "Compras, Ventas y Eventos PPA" },
            { "capacityUnit", "Bbl" },
            { "CreateRelationship", "crear relación" },
            { "DeleteTransferPoint", "eliminar relación" },
            { "TransferPoint", "TransferPoint" },
            { "Edit Node", "Editar nodo" },
            { "Contractual configuration", "Configuración contractual" },
            { "Node States", "Estados de los nodos" },
            { "TipoAtributo", "AttributeType" },
            { "TransactionsAudit", "Auditoría de movimientos e inventarios" },
            { "Select", "Seleccionar" },
            { "Relationship Movements Types", "Relación tipos de movimientos" },
            { "Create a new relationship of movement types", "crear nueva relación de tipos de movimientos" },
            { "Movements type", "Tipo de movimiento" },
            { "Cancellation type", "Tipo de anulación" },
            { "Source", "Origen" },
            { "Destination", "Destino" },
            { "Source product", "Producto origen" },
            { "Destination product", "Producto destino" },
            { "Green", "success" },
            { "Warning", "warning" },
            { "Red", "error" },
            { "TotalNumberOfNodes", "2" },
            { "Audit Configuration", "Auditoría de configuraciones" },
            { "Type of movement", "Tipo de movimiento" },
            { "Type of annulation", "Tipo de anulación" },
            { "Source Prod.", "Prod. Origen" },
            { "Destination Prod.", "Prod. Destino" },
            { "Calculation of deltas by operational adjust", "Cálculo de deltas por ajuste operativo" },
            { "Edit relationship of movement types", "editar relación de tipos de movimientos" },
            { "Segment configuration in TRUE as SON", "Configuración de segmentos en TRUE como SON" },
            { "DeltaCalculation", "Cálculo de deltas por ajuste operativo" },
            { "Calculation of deltas by official adjustment", "Cálculo de deltas por ajuste oficial" },
            { "Official deltas by node", "Deltas oficiales por nodo" },
            { "Official balance per node", "Balance oficial por nodo" },
            { "Official initial balance charged", "Balance oficial inicial cargado" },
            { "Official pending from previous periods", "Pendientes oficiales de períodos anteriores" },
            { "Balance oficial por nodo", "Balance oficial por nodo" },
            { "Edit product priority", "editar la prioridad del producto" },
            { "Approval of the official balance by node", "Aprobación del balance oficial por nodo" },
            { "Official logistics movements and inventories", "Movimientos e inventarios logísticos oficiales" },
        };

        public static Dictionary<string, string> GridPosition { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Name", "1" },
            { "Description", "2" },
            { "CreatedDate", "3" },
            { "isActive", "4" },
            { "isGrouper", "5" },
            { "Priority", "5" },
            { "New Property Function", "5" },
            { "IdentifiedLosses", "5" },
            { "UnIdentifiedLosses", "7" },
            { "FinalInventory", "8" },
            { "OutputTolerance", "6" },
            { "NodeSegment", "1" },
            { "NodeName", "2" },
            { "NodeTypeName", "3" },
            { "Operator", "4" },
            { "TicketId", "1" },
            { "Segment", "2" },
            { "categoryElement_name", "2" },
            { "StartDate", "3" },
            { "EndDate", "4" },
            { "TicketCreatedDate", "5" },
            { "CreatedBy", "6" },
            { "Status", "7" },
            { "SegmentNameOfOwnershipCalculationForSegments", "2" },
            { "StartDateOfOwnershipCalculationForSegments", "3" },
            { "EndDateOfOwnershipCalculationForSegments", "4" },
            { "ExecutionDateOfOwnershipCalculationForSegments", "5" },
            { "UsernameOfOwnershipCalculationForSegments", "6" },
            { "StatusOfOwnershipCalculationForSegments", "7" },
            { "OwnershipRule", "5" },
            { "Error", "2" },
            { "OwnershipStrategy", "5" },
            { "ExcelFileName", "5" },
            { "OwnerName", "1" },
            { "OwnershipStrategyInformation", "6" },
            { "RecordId", "2" },
            { "Contractual configuration", "6" },
            { "Type of movement", "1" },
            { "Type of annulation", "2" },
            { "DeltaSegment", "2" },
            { "DeltaStartDate", "3" },
            { "DeltaEndDate", "4" },
            { "DeltaExecutionDate", "5" },
            { "DeltaStatus", "7" },
            { "DeltaTicket", "1" },
            { "DeltaUser", "6" },
            { "OfficialDeltaStatus", "7" },
            { "LogisticsOfficialStatus", "8" },
        };

        public static Dictionary<string, string> CategoryElementsGridPosition { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Name", "1" },
            { "Description", "2" },
            { "CreatedDate", "3" },
            { "Category", "4" },
            { "isActive", "5" },
            { "State", "5" },
            { "TicketId", "1" },
            { "categoryElement_name", "2" },
            { "StartDate", "3" },
            { "EndDate", "4" },
            { "TicketCreatedDate", "5" },
            { "CreatedBy", "6" },
            { "Status", "7" },
        };

        public static Dictionary<string, string> FilterValueConversion { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "SegmentElement", "SegmentName" },
            { "OperatorElement", "OperatorName" },
            { "NodeTypeElement", "NodeTypeName" },
        };

        public static Dictionary<string, string> GetRow { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "InventoriesByTicketId", SqlQueries.GetInventoryByTicketId },
            { "MovementsByTicketId", SqlQueries.GetMovementsByTicketId },
            { "MovementsByTicketIdAndInterface", SqlQueries.GetMovementsByTicketIdAndInterface },
            { "MovementsByTicketIdAndTolerance", SqlQueries.GetMovementsByTicketIdAndTolerance },
            { "MovementsByTicketIdAndPNI", SqlQueries.GetMovementsByTicketIdAndPNI },
            { "FirstNode", SqlQueries.GetFirstNode },
            { "IconByName", SqlQueries.GetIconByName },
            { "CategoryElementByName", SqlQueries.GetCategoryElementByName },
            { "GetMovementByMovementId", SqlQueries.GetMovementId },
            { "GetSapTrackingByMovementTransactionId", SqlQueries.GetSapTrackingByMovementTransactionId },
        };

        public static Dictionary<string, string> DeleteRow { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "CategoryElementByName", SqlQueries.DeleteCategoryElementByName },
        };

        public static Dictionary<string, string> DirectPageUrl { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Category", "/category/manage" },
            { "Category elements", "/categoryelements/manage" },
            { "Configure group nodes", "/nodetags/manage" },
            { "Configure attributes nodes", "/nodeattributes/manage" },
            { "Configure connections attributes", "/connectionattributes/manage" },
            { "Operational Cutoff", "/cutoff/manage" },
            { "FileUpload", "/fileupload/manage" },
            { "Nodes", "/nodes/manage" },
            { "InternalServerError", "/error/unknown" },
            { "node", "node" },
            { "createuser", "/createuser" },
            { "Relationship Movements Types", "/annulations/manage" },
            { "InvalidExceptions", "/exceptions/manage/666" },
            { "InvalidContracts", "/transportcontracts/manage/666" },
            { "InvalidFileUpload", "/fileupload/manage/666" },
            { "InvalidCutOff", "/cutoff/manage/666" },
            { "Official deltas by node", "/officialdeltapernode/manage" },
            { "Calculation of deltas by official adjustment", "/officialdelta/manage" },
        };

        public static Dictionary<string, string> OwnershipCalculationGrid { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "ene", "01" },
            { "feb", "02" },
            { "mar", "03" },
            { "abr", "04" },
            { "may", "05" },
            { "jun", "06" },
            { "jul", "07" },
            { "ago", "08" },
            { "sep", "09" },
            { "oct", "10" },
            { "nov", "11" },
            { "dic", "12" },
            { "TicketId", "1" },
            { "categoryElement_name", "2" },
            { "StartDate", "2" },
            { "EndDate", "3" },
            { "TicketCreatedDate", "4" },
            { "CreatedBy", "5" },
            { "node_name", "6" },
            { "Segment", "7" },
            { "Status", "8" },
        };

        public static Dictionary<string, string> ReportLogisticGrid { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "ene", "01" },
            { "feb", "02" },
            { "mar", "03" },
            { "abr", "04" },
            { "may", "05" },
            { "jun", "06" },
            { "jul", "07" },
            { "ago", "08" },
            { "sep", "09" },
            { "oct", "10" },
            { "nov", "11" },
            { "dic", "12" },
            { "Segment", "1" },
            { "Owner", "3" },
            { "StartDate", "4" },
            { "EndDate", "5" },
            { "TicketCreatedDate", "6" },
            { "CreatedBy", "7" },
            { "Status", "8" },
            { "Node", "2" },
            { "LogisticsPeriod", "4" },
            { "Error", "5" },
            { "NumberOfErrorRecords", "6" },
        };

        public static Dictionary<string, string> Navigation { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Category", "Administración" },
            { "Category Elements", "Administración" },
            { "Nodes", "Administración" },
            { "CreateNodes", "Administración" },
            { "ConfigureAttributesNodes", "Administración" },
            { "Configure attributes nodes", "Administración" },
            { "Grouping Categories", "Administración" },
            { "Configure group nodes", "Administración" },
            { "nodetags", "Administración" },
            { "ConfigureAttributesConnections", "Administración" },
            { "Configure connections attributes", "Administración" },
            { "Exceptions", "Administración" },
            { "Graphic Network Configuration", "Administración" },
            { "TransformSettings", "Balance de ductos y estaciones" },
            { "FileUpload", "Balance de ductos y estaciones" },
            { "FileUploadForSalesAndPurchases", "Balance de ductos y estaciones" },
            { "FileUploadForPlanningAndProgrammingAndCollaborationAgreements", "Balance de ductos y estaciones" },
            { "Operational Cutoff", "Balance de ductos y estaciones" },
            { "Ownershipcalculation", "Balance de ductos y estaciones" },
            { "Volumetric Balance with ownership for node", "Balance de ductos y estaciones" },
            { "Logistic Report Generation", "Balance de ductos y estaciones" },
            { "Purchases Sales and Events PPA", "Balance de ductos y estaciones" },
            { "Configuration of transfer points - logistic nodes", "Administración" },
            { "Node States", "Reportes de ductos y estaciones" },
            { "Audit Configuration", "Administración" },
            { "TransactionsAudit", "Gestión cadena de suministro" },
            { "Relationship Movements Types", "Administración" },
            { "DeltaCalculation", "Balance de ductos y estaciones" },
            { "Calculation of deltas by operational adjust", "Balance de ductos y estaciones" },
            { "Segment configuration in TRUE as SON", "Administración" },
            { "Operating balance with or without property", "Reportes de ductos y estaciones" },
            { "Property determination by segment", "Balance de ductos y estaciones" },
            { "Control letter", "Reportes de ductos y estaciones" },
            { "Operating balance with ownership per node", "Balance de ductos y estaciones" },
            { "Approval of balance with ownership by node", "Balance de ductos y estaciones" },
            { "Official deltas by node", "Gestión cadena de suministro" },
            { "Calculation of deltas by official adjustment", "Gestión cadena de suministro" },
            { "Official balance per node", "Gestión cadena de suministro" },
            { "Official initial balance charged", "Gestión cadena de suministro" },
            { "Official pending from previous periods", "Gestión cadena de suministro" },
            { "Balance oficial por nodo", "Gestión cadena de suministro" },
            { "Supply chain management", "Gestión cadena de suministro" },
            { "Approval of the official balance by node", "Aprobación del balance oficial por nodo" },
            { "Official logistics movements and inventories", "Gestión cadena de suministro" },
        };

        public static Dictionary<string, string> FileName { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "Movement", "MovementExcel" },
            { "Inventory", "InventoryExcel" },
            { "InventoryWithoutTankNameBatchId", "BatchIdTankNameValidation" },
            { "InventoryWithBothTankNameBatchId", "BatchIdTankNameValidation" },
            { "InventoryWithOnlyBatchId", "BatchIdTankNameValidation" },
            { "InventoryWithOnlyTankName", "BatchIdTankNameValidation" },
            { "InventoryWithTwoDifferentProductsButSameTankNameBatchId", "BatchIdTankNameValidationWithTwoDifferentProducts" },
        };

        public static Dictionary<string, string> UpdateRow { get; } = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "UpdateGlobalMovementId", SqlQueries.UpdateGlobalMovementId },
            { "UpdateErrorInSapTracking", SqlQueries.UpdateErrorInSapTracking },
        };
    }
}