/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

IF	OBJECT_ID('Admin.FeatureRole') IS NOT NULL
BEGIN

-- Clearing any junk data from the reserved space
--DELETE FROM [Admin].[FeatureRole] WHERE FeatureRoleId > 11 AND FeatureRoleId < 101

-- Inserting Seed data with Identity
SET IDENTITY_INSERT [Admin].[FeatureRole] ON 

IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '1')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (1, 1, 1, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '1' AND (RoleId <> '1' OR FeatureId <> '1'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 1 WHERE [FeatureRoleId] = 1	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '2')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (2, 1, 2, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '2' AND (RoleId <> '1' OR FeatureId <> '2'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 2 WHERE [FeatureRoleId] = 2	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '3')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (3, 1, 3, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '3' AND (RoleId <> '1' OR FeatureId <> '3'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 3 WHERE [FeatureRoleId] = 3	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '4')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (4, 1, 4, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '4' AND (RoleId <> '1' OR FeatureId <> '4'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 4 WHERE [FeatureRoleId] = 4	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '5')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (5, 1, 5, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '5' AND (RoleId <> '1' OR FeatureId <> '5'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 5 WHERE [FeatureRoleId] = 5	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '6')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (6, 1, 6, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '6' AND (RoleId <> '1' OR FeatureId <> '6'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 6 WHERE [FeatureRoleId] = 6	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '7')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (7, 1, 7, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '7' AND (RoleId <> '1' OR FeatureId <> '7'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 7 WHERE [FeatureRoleId] = 7	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '8')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (8, 1, 8, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '8' AND (RoleId <> '1' OR FeatureId <> '8'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 8 WHERE [FeatureRoleId] = 8	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '9')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (9, 3, 6, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '9' AND (RoleId <> '3' OR FeatureId <> '6'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 6 WHERE [FeatureRoleId] = 9	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '10')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (10, 3, 7, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '10' AND (RoleId <> '3' OR FeatureId <> '7'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 7 WHERE [FeatureRoleId] = 10	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '11')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (11, 1, 9, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '11' AND (RoleId <> '1' OR FeatureId <> '9'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 9 WHERE [FeatureRoleId] = 11	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '12')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (12, 3, 9, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '12' AND (RoleId <> '3' OR FeatureId <> '9'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 9 WHERE [FeatureRoleId] = 12	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '13')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (13, 3, 10, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '13' AND (RoleId <> '3' OR FeatureId <> '10'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 10 WHERE [FeatureRoleId] = 13	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '14')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (14, 1, 11, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '14' AND (RoleId <> '1' OR FeatureId <> '11'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 11 WHERE [FeatureRoleId] = 14	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '15')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (15, 3, 12, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '15' AND (RoleId <> '3' OR FeatureId <> '12'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 12 WHERE [FeatureRoleId] = 15	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '16')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (16, 1, 13, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '16' AND (RoleId <> '1' OR FeatureId <> '13'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 13 WHERE [FeatureRoleId] = 16	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '17')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (17, 1, 14, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '17' AND (RoleId <> '1' OR FeatureId <> '14'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 14 WHERE [FeatureRoleId] = 17	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '18')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (18, 3, 13, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '18' AND (RoleId <> '3' OR FeatureId <> '13'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 13 WHERE [FeatureRoleId] = 18	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '19')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (19, 3, 14, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '19' AND (RoleId <> '3' OR FeatureId <> '14'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 14 WHERE [FeatureRoleId] = 19	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '20')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (20, 1, 10, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '20' AND (RoleId <> '1' OR FeatureId <> '10'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 10 WHERE [FeatureRoleId] = 20	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '21')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (21, 1, 12, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '21' AND (RoleId <> '1' OR FeatureId <> '12'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 12 WHERE [FeatureRoleId] = 21	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '22')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (22, 3, 11, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '22' AND (RoleId <> '3' OR FeatureId <> '11'))	BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 11 WHERE [FeatureRoleId] = 22	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '24')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (24, 5, 9, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '24' AND (RoleId <> '5' OR FeatureId <> '9'))		BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 9 WHERE [FeatureRoleId] = 24	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '25')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (25, 1, 15, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '25' AND (RoleId <> '1' OR FeatureId <> '15'))		BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 15 WHERE [FeatureRoleId] = 25	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '26')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (26, 1, 16, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '26' AND (RoleId <> '1' OR FeatureId <> '16'))		BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 16 WHERE [FeatureRoleId] = 26	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '27')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (27, 3, 16, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '27' AND (RoleId <> '3' OR FeatureId <> '16'))		BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 16 WHERE [FeatureRoleId] = 27	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '28')	BEGIN	INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (28, 1, 17, N'System', @CurrentTime);	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '28' AND (RoleId <> '1' OR FeatureId <> '17'))		BEGIN	UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 17 WHERE [FeatureRoleId] = 28	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '31')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (31, 1, 18, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '31' AND (RoleId <> '1' OR FeatureId <> '18'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 18 WHERE [FeatureRoleId] = 31    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '36')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (36, 1, 21, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '36' AND (RoleId <> '1' OR FeatureId <> '21'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 21 WHERE [FeatureRoleId] = 36    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '38')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (38, 1, 23, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '38' AND (RoleId <> '1' OR FeatureId <> '23'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 23 WHERE [FeatureRoleId] = 38    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '39')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (39, 1, 24, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '39' AND (RoleId <> '1' OR FeatureId <> '24'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 24 WHERE [FeatureRoleId] = 39    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '40')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (40, 2, 24, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '40' AND (RoleId <> '2' OR FeatureId <> '24'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 2,[FeatureId] = 24 WHERE [FeatureRoleId] = 40    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '41')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (41, 1, 25, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '41' AND (RoleId <> '1' OR FeatureId <> '25'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 25 WHERE [FeatureRoleId] = 41    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '42')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (42, 3, 25, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '42' AND (RoleId <> '3' OR FeatureId <> '25'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 25 WHERE [FeatureRoleId] = 42    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '43')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (43, 1, 26, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '43' AND (RoleId <> '1' OR FeatureId <> '26'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 26 WHERE [FeatureRoleId] = 43    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '44')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (44, 5, 26, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '44' AND (RoleId <> '5' OR FeatureId <> '26'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 26 WHERE [FeatureRoleId] = 44    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '45')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (45, 1, 27, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '45' AND (RoleId <> '1' OR FeatureId <> '27'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 27 WHERE [FeatureRoleId] = 45    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '46')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (46, 5, 25, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '46' AND (RoleId <> '5' OR FeatureId <> '25'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 25 WHERE [FeatureRoleId] = 46    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '47')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (47, 3, 18, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '47' AND (RoleId <> '3' OR FeatureId <> '18'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 18 WHERE [FeatureRoleId] = 47    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '48')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (48, 5, 18, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '48' AND (RoleId <> '5' OR FeatureId <> '18'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 18 WHERE [FeatureRoleId] = 48    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '49')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (49, 3, 26, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '49' AND (RoleId <> '3' OR FeatureId <> '26'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 26 WHERE [FeatureRoleId] = 49    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '50')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (50, 5, 16, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '50' AND (RoleId <> '5' OR FeatureId <> '16'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 16 WHERE [FeatureRoleId] = 50    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '51')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (51, 1, 28, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '51' AND (RoleId <> '1' OR FeatureId <> '28'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 28 WHERE [FeatureRoleId] = 51    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '52')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (52, 1, 29, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '52' AND (RoleId <> '1' OR FeatureId <> '29'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 29 WHERE [FeatureRoleId] = 52    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '53')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (53, 3, 29, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '53' AND (RoleId <> '3' OR FeatureId <> '29'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 29 WHERE [FeatureRoleId] = 53    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '54')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (54, 5, 29, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '54' AND (RoleId <> '5' OR FeatureId <> '29'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 29 WHERE [FeatureRoleId] = 54    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '55')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (55, 1, 30, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '55' AND (RoleId <> '1' OR FeatureId <> '30'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 30 WHERE [FeatureRoleId] = 55    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '56')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (56, 3, 30, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '56' AND (RoleId <> '3' OR FeatureId <> '30'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 30 WHERE [FeatureRoleId] = 56    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '57')    BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (57, 5, 30, N'System', @CurrentTime);    END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '57' AND (RoleId <> '5' OR FeatureId <> '30'))        BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 30 WHERE [FeatureRoleId] = 57    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '58')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (58, 3, 15, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '58' AND (RoleId <> '3' OR FeatureId <> '15'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 15 WHERE [FeatureRoleId] = 58	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '59')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (59, 1, 31, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '59' AND (RoleId <> '1' OR FeatureId <> '31'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 31 WHERE [FeatureRoleId] = 59	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '60')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (60, 1, 32, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '60' AND (RoleId <> '1' OR FeatureId <> '32'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 32 WHERE [FeatureRoleId] = 60	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '61')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (61, 1, 33, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '61' AND (RoleId <> '1' OR FeatureId <> '33'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 33 WHERE [FeatureRoleId] = 61	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '62')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (62, 7, 16, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '62' AND (RoleId <> '7' OR FeatureId <> '16'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 16 WHERE [FeatureRoleId] = 62	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '63')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (63, 6, 31, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '63' AND (RoleId <> '6' OR FeatureId <> '31'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 6,[FeatureId] = 31 WHERE [FeatureRoleId] = 63	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '64')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (64, 6, 33, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '64' AND (RoleId <> '6' OR FeatureId <> '33'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 6,[FeatureId] = 33 WHERE [FeatureRoleId] = 64	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '65')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (65, 1, 34, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '65' AND (RoleId <> '1' OR FeatureId <> '34'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 34 WHERE [FeatureRoleId] = 65	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '66')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (66, 3, 34, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '66' AND (RoleId <> '3' OR FeatureId <> '34'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 34 WHERE [FeatureRoleId] = 66	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '67')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (67, 1, 35, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '67' AND (RoleId <> '1' OR FeatureId <> '35'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 35 WHERE [FeatureRoleId] = 67	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '68')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (68, 1, 36, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '68' AND (RoleId <> '1' OR FeatureId <> '36'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 36 WHERE [FeatureRoleId] = 68	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '69')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (69, 1, 37, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '69' AND (RoleId <> '1' OR FeatureId <> '37'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 37 WHERE [FeatureRoleId] = 69	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '70')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (70, 1, 38, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '70' AND (RoleId <> '1' OR FeatureId <> '38'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 38 WHERE [FeatureRoleId] = 70	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '71')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (71, 5, 38, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '71' AND (RoleId <> '5' OR FeatureId <> '38'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 38 WHERE [FeatureRoleId] = 71	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '72')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (72, 1, 39, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '72' AND (RoleId <> '1' OR FeatureId <> '39'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 39 WHERE [FeatureRoleId] = 72	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '73')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (73, 1, 40, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '73' AND (RoleId <> '1' OR FeatureId <> '40'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 40 WHERE [FeatureRoleId] = 73	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '74')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (74, 5, 40, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '74' AND (RoleId <> '5' OR FeatureId <> '40'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 40 WHERE [FeatureRoleId] = 74	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '75')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (75, 1, 41, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '75' AND (RoleId <> '1' OR FeatureId <> '41'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 41 WHERE [FeatureRoleId] = 75	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '76')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (76, 5, 41, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '76' AND (RoleId <> '5' OR FeatureId <> '41'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 41 WHERE [FeatureRoleId] = 76	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '77')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (77, 1, 42, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '77' AND (RoleId <> '1' OR FeatureId <> '42'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 42 WHERE [FeatureRoleId] = 77	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '78')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (78, 5, 42, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '78' AND (RoleId <> '5' OR FeatureId <> '42'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 42 WHERE [FeatureRoleId] = 78	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '79')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (79, 7, 36, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '79' AND (RoleId <> '7' OR FeatureId <> '36'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 36 WHERE [FeatureRoleId] = 79	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '80')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (80, 7, 37, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '80' AND (RoleId <> '7' OR FeatureId <> '37'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 37 WHERE [FeatureRoleId] = 80	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '81')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (81, 7, 39, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '81' AND (RoleId <> '7' OR FeatureId <> '39'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 39 WHERE [FeatureRoleId] = 81	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '82')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (82, 7, 40, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '82' AND (RoleId <> '7' OR FeatureId <> '40'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 40 WHERE [FeatureRoleId] = 82	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '83')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (83, 7, 41, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '83' AND (RoleId <> '7' OR FeatureId <> '41'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 41 WHERE [FeatureRoleId] = 83	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '84')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (84, 7, 42, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '84' AND (RoleId <> '7' OR FeatureId <> '42'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 42 WHERE [FeatureRoleId] = 84	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '85')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (85, 1, 43, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '85' AND (RoleId <> '1' OR FeatureId <> '43'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 43 WHERE [FeatureRoleId] = 85	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '86')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (86, 6, 43, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '86' AND (RoleId <> '6' OR FeatureId <> '43'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 6,[FeatureId] = 43 WHERE [FeatureRoleId] = 86	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '87')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (87, 1, 44, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '87' AND (RoleId <> '1' OR FeatureId <> '44'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 44 WHERE [FeatureRoleId] = 87	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '88')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (88, 2, 44, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '88' AND (RoleId <> '2' OR FeatureId <> '44'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 2,[FeatureId] = 44 WHERE [FeatureRoleId] = 88	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '89')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (89, 1, 45, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '89' AND (RoleId <> '1' OR FeatureId <> '45'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 45 WHERE [FeatureRoleId] = 89	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '90')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (90, 3, 45, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '90' AND (RoleId <> '3' OR FeatureId <> '45'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 45 WHERE [FeatureRoleId] = 90	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '91')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (91, 7, 45, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '91' AND (RoleId <> '7' OR FeatureId <> '45'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 45 WHERE [FeatureRoleId] = 91	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '92')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (92, 4, 13, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '92' AND (RoleId <> '4' OR FeatureId <> '13'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 4,[FeatureId] = 13 WHERE [FeatureRoleId] = 92	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '93')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (93, 4, 12, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '93' AND (RoleId <> '4' OR FeatureId <> '12'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 4,[FeatureId] = 12 WHERE [FeatureRoleId] = 93	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '94')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (94, 4, 25, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '94' AND (RoleId <> '4' OR FeatureId <> '25'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 4,[FeatureId] = 25 WHERE [FeatureRoleId] = 94	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '95')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (95, 4, 9, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '95' AND (RoleId <> '4' OR FeatureId <> '9'))		    BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 4,[FeatureId] = 9  WHERE [FeatureRoleId] = 95	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '96')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (96, 4, 39, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '96' AND (RoleId <> '4' OR FeatureId <> '39'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 4,[FeatureId] = 39 WHERE [FeatureRoleId] = 96	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '97')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (97, 1, 46, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '97' AND (RoleId <> '1' OR FeatureId <> '46'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 46 WHERE [FeatureRoleId] = 97	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '98')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (98, 1, 47, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '98' AND (RoleId <> '1' OR FeatureId <> '47'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 47 WHERE [FeatureRoleId] = 98	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '99')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (99, 4, 46, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '99' AND (RoleId <> '4' OR FeatureId <> '46'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 4,[FeatureId] = 46 WHERE [FeatureRoleId] = 99	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '100')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (100, 5, 46, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '100' AND (RoleId <> '5' OR FeatureId <> '46'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 46 WHERE [FeatureRoleId] = 100	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '101')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (101, 7, 46, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '101' AND (RoleId <> '7' OR FeatureId <> '46'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 46 WHERE [FeatureRoleId] = 101	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '102')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (102, 3, 47, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '102' AND (RoleId <> '3' OR FeatureId <> '47'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 3,[FeatureId] = 47 WHERE [FeatureRoleId] = 102	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '103')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (103, 5, 47, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '103' AND (RoleId <> '5' OR FeatureId <> '47'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 47 WHERE [FeatureRoleId] = 103	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '104')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (104, 4, 47, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '104' AND (RoleId <> '4' OR FeatureId <> '47'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 4,[FeatureId] = 47 WHERE [FeatureRoleId] = 104	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '105')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (105, 5, 39, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '105' AND (RoleId <> '5' OR FeatureId <> '39'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 39 WHERE [FeatureRoleId] = 105	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '106')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (106, 7, 48, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '106' AND (RoleId <> '7' OR FeatureId <> '48'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 48 WHERE [FeatureRoleId] = 106	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '107')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (107, 1, 48, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '107' AND (RoleId <> '1' OR FeatureId <> '48'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 48 WHERE [FeatureRoleId] = 107	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '108')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (108, 1, 49, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '108' AND (RoleId <> '1' OR FeatureId <> '49'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 49 WHERE [FeatureRoleId] = 108	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '109')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (109, 1, 50, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '109' AND (RoleId <> '1' OR FeatureId <> '50'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 50 WHERE [FeatureRoleId] = 109	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '110')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (110, 5, 50, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '110' AND (RoleId <> '5' OR FeatureId <> '50'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 50 WHERE [FeatureRoleId] = 110	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '111')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (111, 7, 50, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '111' AND (RoleId <> '7' OR FeatureId <> '50'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 50 WHERE [FeatureRoleId] = 111	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '112')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (112, 1, 51, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '112' AND (RoleId <> '1' OR FeatureId <> '51'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 51 WHERE [FeatureRoleId] = 112	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '113')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (113, 6, 51, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '113' AND (RoleId <> '6' OR FeatureId <> '51'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 6,[FeatureId] = 51 WHERE [FeatureRoleId] = 113	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '114')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (114, 1, 52, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '114' AND (RoleId <> '1' OR FeatureId <> '52'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 52 WHERE [FeatureRoleId] = 114	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '116')   BEGIN    INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (116, 1, 55, N'System', @CurrentTime);   END    ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '116' AND (RoleId <> '1' OR FeatureId <> '55'))       BEGIN    UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 55 WHERE [FeatureRoleId] = 116   END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '117')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (117, 1, 53, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '117' AND (RoleId <> '1' OR FeatureId <> '53'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 1,[FeatureId] = 53 WHERE [FeatureRoleId] = 117	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '118')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (118, 5, 53, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '118' AND (RoleId <> '5' OR FeatureId <> '53'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 5,[FeatureId] = 53 WHERE [FeatureRoleId] = 118	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '119')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (119, 7, 53, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '119' AND (RoleId <> '7' OR FeatureId <> '53'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 7,[FeatureId] = 53 WHERE [FeatureRoleId] = 119	  END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '120')	  BEGIN	   INSERT [Admin].[FeatureRole] ([FeatureRoleId], [RoleId], [FeatureId], [CreatedBy], [CreatedDate]) VALUES (120, 6, 46, N'System', @CurrentTime);	 END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[FeatureRole] WHERE [FeatureRoleId] = '120' AND (RoleId <> '6' OR FeatureId <> '46'))		BEGIN	 UPDATE [Admin].[FeatureRole] SET [RoleId] = 6,[FeatureId] = 46 WHERE [FeatureRoleId] = 120	  END

SET IDENTITY_INSERT [Admin].[FeatureRole] OFF
END