/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

IF	OBJECT_ID('Admin.HomologationObjectType') IS NOT NULL
BEGIN

IF EXISTS (SELECT 1 
					FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
					WHERE CONSTRAINT_TYPE='UNIQUE'
					AND CONSTRAINT_NAME = 'UC_HomologationObjectType')
		BEGIN
			EXEC sp_executesql N'ALTER TABLE [Admin].[HomologationObjectType]
			DROP CONSTRAINT UC_HomologationObjectType';
		END


-- Inserting Seed data with Identity
SET IDENTITY_INSERT [Admin].[HomologationObjectType] ON 

IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '1')		BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (1, N'EventTypeId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '1' AND (Name <> 'EventTypeId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'EventTypeId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 1	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '2')		BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (2, N'NodeId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '2' AND (Name <> 'NodeId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'NodeId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 2	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '3')		BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (3, N'ProductId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '3' AND (Name <> 'ProductId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'ProductId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 3	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '4')		BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (4, N'ProductType', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '4' AND (Name <> 'ProductType'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'ProductType', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 4	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '5')		BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (5, N'MeasurementUnit', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '5' AND (Name <> 'MeasurementUnit'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'MeasurementUnit', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 5	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '6')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (6, N'AttributeId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '6' AND (Name <> 'AttributeId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'AttributeId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 6	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '7')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (7, N'ValueAttributeUnit', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '7' AND (Name <> 'ValueAttributeUnit'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'ValueAttributeUnit', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 7	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '8')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (8, N'OwnerId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '8' AND (Name <> 'OwnerId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'OwnerId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 8	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '9')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (9, N'OwnershipValueUnit', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '9' AND (Name <> 'OwnershipValueUnit'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'OwnershipValueUnit', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 9	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '10')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (10, N'SourceNodeId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '10' AND (Name <> 'SourceNodeId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'SourceNodeId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 10	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '11')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (11, N'SourceProductId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '11' AND (Name <> 'SourceProductId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'SourceProductId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 11	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '12')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (12, N'SourceProductTypeId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '12' AND (Name <> 'SourceProductTypeId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'SourceProductTypeId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 12	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '13')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (13, N'DestinationNodeId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '13' AND (Name <> 'DestinationNodeId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'DestinationNodeId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 13	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '14')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (14, N'DestinationProductId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '14' AND (Name <> 'DestinationProductId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'DestinationProductId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 14	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '15')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (15, N'DestinationProductTypeId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '15' AND (Name <> 'DestinationProductTypeId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'DestinationProductTypeId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 15	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '16')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (16, N'NodeStorageLocationId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '16' AND (Name <> 'NodeStorageLocationId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'NodeStorageLocationId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 16	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '17')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (17, N'StorageLocationProductId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '17' AND (Name <> 'StorageLocationProductId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'StorageLocationProductId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 17	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '18')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (18, N'MovementTypeId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '18' AND (Name <> 'MovementTypeId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'MovementTypeId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 18	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '19')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (19, N'CommercialId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '19' AND (Name <> 'CommercialId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'CommercialId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 19	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '20')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (20, N'SegmentId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '20' AND (Name <> 'SegmentId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'SegmentId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 20	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '21')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (21, N'Owner1Id', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '21' AND (Name <> 'Owner1Id'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'Owner1Id', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 21	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '22')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (22, N'Owner2Id', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '22' AND (Name <> 'Owner2Id'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'Owner2Id', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 22	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '23')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (23, N'SystemId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '23' AND (Name <> 'SystemId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'SystemId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 23	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '24')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (24, N'OperatorId', N'System', @CurrentTime, NULL, NULL)	    END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '24' AND (Name <> 'OperatorId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'OperatorId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 24	    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '25')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (25, N'SourceStorageLocationId', N'System', @CurrentTime, NULL, NULL)	        END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '25' AND (Name <> 'SourceStorageLocationId'))	    BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'SourceStorageLocationId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 25	    END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '26')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (26, N'DestinationStorageLocationId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '26' AND (Name <> 'DestinationStorageLocationId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'DestinationStorageLocationId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 26	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '27')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (27, N'SourceSystemId', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '27' AND (Name <> 'SourceSystemId'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'SourceSystemId', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 27	END

IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '28')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (28, N'PurchaseOrderType', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '28' AND (Name <> 'PurchaseOrderType'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'PurchaseOrderType', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 28	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '29')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (29, N'ExpeditionClass', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '29' AND (Name <> 'ExpeditionClass'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'ExpeditionClass', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 29 END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '30')	BEGIN	INSERT [Admin].[HomologationObjectType] ([HomologationObjectTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (30, N'Uom', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[HomologationObjectType] WHERE [HomologationObjectTypeId] = '30' AND (Name <> 'Uom'))	BEGIN	UPDATE [Admin].[HomologationObjectType] SET [Name] = 'Uom', [LastModifiedBy] = 'System', [LastModifiedDate] = @CurrentTime WHERE [HomologationObjectTypeId] = 30 END

SET IDENTITY_INSERT [Admin].[HomologationObjectType] OFF

IF NOT EXISTS (SELECT 1
                    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
                    WHERE CONSTRAINT_TYPE='UNIQUE'
                    AND CONSTRAINT_NAME = 'UC_HomologationObjectType')
        BEGIN
            ALTER TABLE [Admin].[HomologationObjectType]
            ADD CONSTRAINT [UC_HomologationObjectType] UNIQUE NONCLUSTERED ([Name])
        END

END
