/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

IF	OBJECT_ID('Admin.NodeStatusIconUrl') IS NOT NULL
BEGIN

-- Inserting Seed data with Identity
SET IDENTITY_INSERT [Admin].[NodeStatusIconUrl] ON 

IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '1')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (1, '$(baseUrl)'+'/dist/images/reports/state1.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state1.png' WHERE [NodeStatusIconUrlId] = 1	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '2')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (2, '$(baseUrl)'+'/dist/images/reports/state2.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state2.png' WHERE [NodeStatusIconUrlId] = 2	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '3')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (3, '$(baseUrl)'+'/dist/images/reports/state3.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state3.png' WHERE [NodeStatusIconUrlId] = 3	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '4')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (4, '$(baseUrl)'+'/dist/images/reports/state4.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state4.png' WHERE [NodeStatusIconUrlId] = 4	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '5')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (5, '$(baseUrl)'+'/dist/images/reports/state5.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state5.png' WHERE [NodeStatusIconUrlId] = 5	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '6')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (6, '$(baseUrl)'+'/dist/images/reports/state6.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state6.png' WHERE [NodeStatusIconUrlId] = 6	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '7')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (7, '$(baseUrl)'+'/dist/images/reports/state7.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state7.png' WHERE [NodeStatusIconUrlId] = 7	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '8')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (8, '$(baseUrl)'+'/dist/images/reports/state8.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state8.png' WHERE [NodeStatusIconUrlId] = 8	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '9')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (9, '$(baseUrl)'+'/dist/images/reports/state9.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state9.png' WHERE [NodeStatusIconUrlId] = 9	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '10')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (10, '$(baseUrl)'+'/dist/images/reports/state10.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state10.png' WHERE [NodeStatusIconUrlId] = 10	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '11')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (11, '$(baseUrl)'+'/dist/images/reports/state11.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state11.png' WHERE [NodeStatusIconUrlId] = 11	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '12')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (12, '$(baseUrl)'+'/dist/images/reports/state12.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state12.png' WHERE [NodeStatusIconUrlId] = 12	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '13')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (13, '$(baseUrl)'+'/dist/images/reports/state13.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state13.png' WHERE [NodeStatusIconUrlId] = 13	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '14')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (14, '$(baseUrl)'+'/dist/images/reports/state14.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state14.png' WHERE [NodeStatusIconUrlId] = 14	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '15')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (15, '$(baseUrl)'+'/dist/images/reports/state15.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state15.png' WHERE [NodeStatusIconUrlId] = 15	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '16')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (16, '$(baseUrl)'+'/dist/images/reports/state16.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state16.png' WHERE [NodeStatusIconUrlId] = 16	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '17')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (17, '$(baseUrl)'+'/dist/images/reports/state17.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state17.png' WHERE [NodeStatusIconUrlId] = 17	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '18')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (18, '$(baseUrl)'+'/dist/images/reports/state18.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state18.png' WHERE [NodeStatusIconUrlId] = 18	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '19')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (19, '$(baseUrl)'+'/dist/images/reports/state19.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state19.png' WHERE [NodeStatusIconUrlId] = 19	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[NodeStatusIconUrl] WHERE [NodeStatusIconUrlId] = '20')	BEGIN	INSERT [Admin].[NodeStatusIconUrl] ([NodeStatusIconUrlId], [NodeStatusIconUrl], [CreatedBy], [CreatedDate]) VALUES (20, '$(baseUrl)'+'/dist/images/reports/state20.png', N'System', @CurrentTime);	END	ELSE BEGIN	UPDATE [Admin].[NodeStatusIconUrl] SET  [NodeStatusIconUrl] = '$(baseUrl)'+'/dist/images/reports/state20.png' WHERE [NodeStatusIconUrlId] = 20	END

SET IDENTITY_INSERT [Admin].[NodeStatusIconUrl] OFF
END	
