/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

IF	OBJECT_ID('Admin.OwnershipNodeStatusType') IS NOT NULL
BEGIN

-- Inserting Seed data with Identity
SET IDENTITY_INSERT [Admin].[OwnershipNodeStatusType] ON 

IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '1')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (1, N'Procesando', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '1' AND ([Name] <> 'Procesando'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Procesando' WHERE [OwnershipNodeStatusTypeId] = 1	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '2')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (2, N'Propiedad', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '2' AND ([Name] <> 'Propiedad'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Propiedad' WHERE [OwnershipNodeStatusTypeId] = 2	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '3')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (3, N'Fallido', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '3' AND ([Name] <> 'Fallido'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Fallido' WHERE [OwnershipNodeStatusTypeId] = 3	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '4')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (4, N'Bloqueado', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '4' AND ([Name] <> 'Bloqueado'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Bloqueado' WHERE [OwnershipNodeStatusTypeId] = 4	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '5')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (5, N'Desbloqueado', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '5' AND ([Name] <> 'Desbloqueado'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Desbloqueado' WHERE [OwnershipNodeStatusTypeId] = 5	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '6')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (6, N'Publicando', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '6' AND ([Name] <> 'Publicando'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Publicando' WHERE [OwnershipNodeStatusTypeId] = 6	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '7')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (7, N'Publicado', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '7' AND ([Name] <> 'Publicado'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Publicado' WHERE [OwnershipNodeStatusTypeId] = 7	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '8')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (8, N'Enviado a aprobación', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '8' AND ([Name] <> 'Enviado a aprobación'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Enviado a aprobación' WHERE [OwnershipNodeStatusTypeId] = 8	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '9')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (9, N'Aprobado', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '9' AND ([Name] <> 'Aprobado'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Aprobado' WHERE [OwnershipNodeStatusTypeId] = 9	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '10')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (10, N'Rechazado', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '10' AND ([Name] <> 'Rechazado'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Rechazado' WHERE [OwnershipNodeStatusTypeId] = 10	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '11')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (11, N'Reabierto', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '11' AND ([Name] <> 'Reabierto'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Reabierto' WHERE [OwnershipNodeStatusTypeId] = 11	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '12')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (12, N'Deltas', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '12' AND ([Name] <> 'Deltas'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Deltas' WHERE [OwnershipNodeStatusTypeId] = 12	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '13')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (13, N'Conciliado', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '13' AND ([Name] <> 'Conciliado'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Conciliado' WHERE [OwnershipNodeStatusTypeId] = 13	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '14')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (14, N'No Conciliado', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '14' AND ([Name] <> 'No Conciliado'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'No Conciliado' WHERE [OwnershipNodeStatusTypeId] = 14	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '15')	BEGIN	INSERT [Admin].[OwnershipNodeStatusType] ([OwnershipNodeStatusTypeId], [Name], [CreatedBy], [CreatedDate]) VALUES (15, N'Fallo Conciliación', N'System', @CurrentTime)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[OwnershipNodeStatusType] WHERE [OwnershipNodeStatusTypeId] = '15' AND ([Name] <> 'Fallo Conciliación'))	BEGIN	UPDATE [Admin].[OwnershipNodeStatusType] SET [Name] = 'Fallo Conciliación' WHERE [OwnershipNodeStatusTypeId] = 15	END

SET IDENTITY_INSERT [Admin].[OwnershipNodeStatusType] OFF
END	

