/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

IF	OBJECT_ID('Admin.SystemType') IS NOT NULL
BEGIN

-- Clearing any junk data from the reserved space
--DELETE FROM [Admin].[SystemType] WHERE SystemTypeId > 3 AND SystemTypeId < 101

-- Inserting Seed data with Identity
SET IDENTITY_INSERT [Admin].[SystemType] ON 

IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 1)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (1, N'TRUE', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '1' AND ([Name] <> 'TRUE'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'TRUE' WHERE [SystemTypeId] = '1'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 2)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (2, N'SINOPER', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '2' AND ([Name] <> 'SINOPER'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'SINOPER' WHERE [SystemTypeId] = '2'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 3)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (3, N'EXCEL', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '3' AND ([Name] <> 'EXCEL'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'EXCEL' WHERE [SystemTypeId] = '3'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 4)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (4, N'Pedidos', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '4' AND ([Name] <> 'Pedidos'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'Pedidos' WHERE [SystemTypeId] = '4'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 5)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (5, N'Planeación, Programación y Acuerdos', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '5' AND ([Name] <> 'Planeación, Programación y Acuerdos'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'Planeación, Programación y Acuerdos' WHERE [SystemTypeId] = '5'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 6)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (6, N'SIV', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '6' AND ([Name] <> 'SIV'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'SIV' WHERE [SystemTypeId] = '6'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 7)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (7, N'SAP PO', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '7' AND ([Name] <> 'SAP PO'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'SAP PO' WHERE [SystemTypeId] = '7'	END
--Nuevos
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 8)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (8, N'ManualInvOficial', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '8' AND ([Name] <> 'ManualInvOficial'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'ManualInvOficial' WHERE [SystemTypeId] = '8'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 9)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (9, N'ManualMovOficial', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '9' AND ([Name] <> 'ManualMovOficial'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'ManualMovOficial' WHERE [SystemTypeId] = '9'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 10)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (10, N'PURCHASE', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '10' AND ([Name] <> 'PURCHASE'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'PURCHASE' WHERE [SystemTypeId] = '10'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 11)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (11, N'SELL', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '11' AND ([Name] <> 'SELL'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'SELL' WHERE [SystemTypeId] = '11'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 12)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (12, N'MOVEMENT', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '12' AND ([Name] <> 'MOVEMENT'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'MOVEMENT' WHERE [SystemTypeId] = '12'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 13)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (13, N'INVENTORY', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '13' AND ([Name] <> 'INVENTORY'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'INVENTORY' WHERE [SystemTypeId] = '13'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 14)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (14, N'LOGISTIC', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '14' AND ([Name] <> 'LOGISTIC'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'LOGISTIC' WHERE [SystemTypeId] = '14'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 15)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (15, N'FICO', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '15' AND ([Name] <> 'FICO'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'FICO' WHERE [SystemTypeId] = '15'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 16)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (16, N'OWNERSHIP', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '16' AND ([Name] <> 'OWNERSHIP'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'OWNERSHIP' WHERE [SystemTypeId] = '16'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 17)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (17, N'OPERATIVEDELTA', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '17' AND ([Name] <> 'OPERATIVEDELTA'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'OPERATIVEDELTA' WHERE [SystemTypeId] = '17'	END
IF NOT EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = 18)	BEGIN	INSERT [Admin].[SystemType] ([SystemTypeId], [Name], [CreatedBy], [CreatedDate], [LastModifiedBy], [LastModifiedDate]) VALUES (18, N'OFFICIALDELTA', N'System', @CurrentTime, NULL, NULL)	END	ELSE IF EXISTS (SELECT 'X' FROM [Admin].[SystemType] WHERE [SystemTypeId] = '18' AND ([Name] <> 'OFFICIALDELTA'))	BEGIN	UPDATE [Admin].[SystemType] SET [Name] = 'OFFICIALDELTA' WHERE [SystemTypeId] = '18'	END

SET IDENTITY_INSERT [Admin].[SystemType] OFF
END	
