variables:
  - group: true-secrets-nonprd-shared
  - group: true-secrets-qas
  - group: true-network-qas
  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/non-prod.yml
  - template: ../Templates/Variables/tags.yml

trigger: none
pr: none
stages:
- template: ../Templates/Stage/infra.build.yml
- template: ../Templates/Stage/infra.shared.deploy.yml