variables:
  - group: true-secrets-prd
  - group: true-network-prd
  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/prod.yml
  - template: ../Templates/Variables/tags.yml

trigger: none
stages:
- template: ../Templates/Stage/infra.build.yml
      
- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
     vmImage: 'windows-latest'
    environment: $(env)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: Drop
              downloadPath: '$(System.ArtifactsDirectory)'

          - template: ../Templates/Deploy/dataScience.deploy.yml
            parameters:
              env: '$(env)'
              serviceConnection : $(serviceConnection)
              vmUsername : '$(userDataScienceVm)'
              vmPassword : '$(vmPassword)'
              vmSubnetName: '$(vmSubnetName)'
              vmVnetId: '$(virtualNetworkId)'
              virtualMachineName: '$(dataScienceVirtualMachineName)'
              vmNicName: '$(dataScienceVirtualMachineNicName)'