variables:
  - group: true-secrets-prd
  - group: true-network-prd
  - group: true-scale-prd
  
  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/prod.yml
  - template: ../Templates/Variables/tags.yml
  - template: ../Templates/Variables/alerts.yml

trigger: none
pr: none

stages:
- template: ../Templates/Stage/infra.build.yml
- template: ../Templates/Stage/infra.deploy.yml