variables:
  - group: true-threshold
  - group: true-secrets-nonprd-shared
  - group: true-secrets-dev
  - group: true-network-dev
  - group: true-automation
  - template: ../../Templates/Variables/package.yml
  - template: ../../Templates/Variables/infra.yml
  - template: ../../Templates/Variables/non-prod.yml

trigger: 
      branches :
       include: 
        - master
      paths:
        include:
         - Develop/Ecp.True/DI/*
         - Deploy/Templates/Data Factory/*

pr: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     vmImage: 'windows-latest'
    steps:
    - template: ../../Templates/Build/build.yml
      parameters:
        db: 'true'
    
    - template: ../../Templates/package.yml
      parameters:
        db: 'true'
        infra: 'true'

- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
     vmImage: 'windows-latest'
    environment: $(env)
    strategy:
      runOnce:
        deploy:
          steps:
          - template: ../../Templates/Deploy/db.deploy.yml
            parameters:
              serviceConnection : $(serviceConnection)
              downloadArtifacts : "true"
              
          - template: ../../Templates/Deploy/aas.deploy.yml
            parameters:
              serviceConnection : $(serviceConnection)
              downloadArtifacts : "false"
              analysisServerModel : $(analysisServerModel)
              analysisServer : $(analysisServer)

          - template: ../../Templates/Deploy/automation.yml 
            parameters:
              azureSubscriptionName : '$(serviceConnection)'
              canExecuteAutomation: '$(dev)'
              keyVaultName: '$(keyVault)'
              automation: 'true'