variables:
- group: true-secrets-nonprd-shared
- group: true-secrets-dev
- group: true-network-dev
- group: true-automation
- template: ../../Templates/Variables/package.yml
- template: ../../Templates/Variables/infra.yml
- template: ../../Templates/Variables/non-prod.yml
- template: ../../Templates/Variables/tags.yml

trigger:
      branches :
       include: 
        - master
      paths:
        include:
         - Develop/Ecp.True/DI/Ecp.True.DI.Report/*
         - Develop/Ecp.True/DI/Ecp.True.DI.Inputs/*
        exclude:
         - Develop/Ecp.True/DI/Ecp.True.DI.Sql/*
         - Develop/Ecp.True/DI/Ecp.True.DI.Analysis/*

pr: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     vmImage: 'windows-latest'
    steps:
    - template: ../../Templates/Build/build.yml
      parameters:
        config: 'true'

    - template: ../../Templates/package.yml
      parameters:
        db: 'true'
        infra: 'true'
      
- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
     vmImage: 'windows-latest'
    environment: $(env)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: Drop
              downloadPath: '$(System.ArtifactsDirectory)'

          - template: ../../Templates/Infra/powerBI.yml 
            parameters:
              env: '$(env)'
              azureSubscriptionName : '$(serviceConnection)'

          - template: ../../Templates/Infra/config.yml 
            parameters:
              env: '$(env)'
              azureSubscriptionName : '$(serviceConnection)'

          - template: ../../Templates/Deploy/automation.yml 
            parameters:
              azureSubscriptionName : '$(serviceConnection)'
              canExecuteAutomation: '$(dev)'
              keyVaultName: '$(keyVault)'
              automation: 'true'