// --------------------------------------------------------------------------------------------------------------------
// <copyright file="DeleteMovementOwnershipSteps.cs" company="Microsoft">
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
//    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
//    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
//    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
//    OTHER DEALINGS IN THE SOFTWARE.
// </copyright>
//<autogenerated>
// --------------------------------------------------------------------------------------------------------------------
namespace Ecp.True.Bdd.Tests.StepDefinitions.UI
{
    using Ecp.True.Bdd.Tests.Properties;

    using global::Bdd.Core.Web.Executors;
    using global::Bdd.Core.Web.Utils;

    using NUnit.Framework;

    using TechTalk.SpecFlow;

    [Binding]
    public class DeleteMovementOwnershipSteps : EcpWebStepDefinitionBase
    {
        [Then(@"it should be marked as deleted")]
        public void ThenItShouldBeMarkedAsDeleted()
        {
            Assert.AreEqual("2", this.Get<ElementPage>().GetElements(nameof(Resources.OwnershipDataGridRows)).Count);
        }
    }
}