apiVersion: v1
kind: Secret
metadata:
  name: aks-analytics-secret
  namespace: #{namespace}#
type: Opaque
data:
  CLIENT_SECRET: #{analyticsAppSecret}#
  CLIENT_ID: #{analyticsAppClientId}#
  TENANT_ID: #{analyticsTenantId}#
  KEY_VAULT: #{analyticsKeyvault}#