kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: #{namespace}#-user-access
  namespace: #{namespace}#
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: #{namespace}#-user-full-access
subjects:
- kind: User
  namespace: #{namespace}#
  name: 8875e610-83fc-468e-b4a5-ca3a9c830964