variables:
  - group: true-threshold
  - template: ../../Templates/Variables/package.yml

trigger: none
stages:
  - stage: Build
    jobs:
      - job: Build
        pool:
          vmImage: 'windows-latest'
        steps:
          - template: ../../Templates/Build/datagenerator.build.yml
