variables:
  - group: true-network-dev
  - group: true-secrets-nonprd-shared
  - group: true-secrets-dev
  - template: ../../Templates/Variables/package.yml
  - template: ../../Templates/Variables/infra.yml

trigger: none

stages:
- template: ../../Templates/Stage/infra.build.yml
  parameters:
    azsk: 'true'

#TODO: 
#YAML files validation