apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
    aadpodidbinding: select_truepod
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        aadpodidbinding: select_truepod
        date: "{{ now | unixEpoch }}"
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              key:  CLIENT_ID
              name: aks-analytics-secret
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key:  CLIENT_SECRET
              name: aks-analytics-secret
        - name: TENANT_ID
          valueFrom:
            secretKeyRef:
              key:  TENANT_ID
              name: aks-analytics-secret
        - name: KEY_VAULT
          valueFrom:
            secretKeyRef:
              key:  KEY_VAULT
              name: aks-analytics-secret
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - containerPort: {{.Values.container.port}}
          name: {{ .Chart.Name }}
        livenessProbe:
          httpGet:
            path: /swagger.json
            port: {{ .Values.container.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /swagger.json
            port: {{ .Values.container.port }}
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
