apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecptrue-ana-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  tls:
    - hosts:
      - {{.Values.HOST_NAME}}
      secretName: aks-ingress-tls
  rules:
  - host: {{.Values.HOST_NAME}}
    http:
      paths:
      - path: /analytics(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port: 
              number: 5000
