variables:
- group: true-release-threshold
- group: true-secrets-stg
- group: true-network-stg
- group: true-automation
- template: ../Templates/Variables/package.yml
- template: ../Templates/Variables/infra.yml
- template: ../Templates/Variables/non-prod-stg.yml

trigger: none
pr: none

stages:
- template: ../Templates/Stage/app.build.yml
- template: ../Templates/Stage/app.deploy.yml
  parameters:
    canExecuteAutomation: '$(stg)'
    automation: 'true'
- template: ../Templates/Stage/app.purge.yml