variables:
- template: non-prod.yml
- name: apimSku
  value: 'Developer'
- name: aasSkuName
  value: 'D1'
- name: aasSku
  value: 'Developer'
- name: abssku
  value: 'B0'
- name: acrSku
  value: 'Basic'
- name: aksAgentPoolVmSize
  value: 'Standard_D2s_v3'
- name: serviceBusSkuName
  value: 'Premium'
- name: signalRCapacity
  value: 1
- name: signalRPricingTier
  value: 'Free_F1'
- name: apiCpuLimits
  value: '2000m'
- name: apiMemoryLimits
  value: '2048Mi'
- name: apiMemoryRequests
  value: '1024Mi'
- name: apiCpuRequests
  value: '1000m'
- name: apiReplicaCount
  value: 1
- name: apiHighCpuLimits
  value: '1000m'
- name: apiHighMemoryLimits
  value: '1024Mi'
- name: apiHighMemoryRequests
  value: '512Mi'
- name: apiHighCpuRequests
  value: '500m'
- name: apiHighReplicaCount
  value: 1
- name: apiMediumCpuLimits
  value: '500m'
- name: apiMediumMemoryLimits
  value: '512Mi'
- name: apiMediumMemoryRequests
  value: '256Mi'
- name: apiMediumCpuRequests
  value: '250m'
- name: apiMediumReplicaCount
  value: 1
- name: apiLowCpuLimits
  value: '500m'
- name: apiLowMemoryLimits
  value: '512Mi'
- name: apiLowMemoryRequests
  value: '256Mi'
- name: apiLowCpuRequests
  value: '250m'
- name: apiLowReplicaCount
  value: 1
- name: absskuName
  value: 'Basic'
- name: disableAlert
  value: false