variables:
  - group: true-secrets-nonprd-shared
  - group: true-secrets-uat
  - group: true-network-uat
  - group: true-scale-nonprd

  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/non-prod.yml
  - template: ../Templates/Variables/tags.yml
  - template: ../Templates/Variables/alerts.yml

trigger: none
pr: none

stages:
- template: ../Templates/Stage/infra.build.yml
- template: ../Templates/Stage/infra.deploy.yml