variables:
  - group: true-secrets-uat
  - group: true-release-threshold
  - group: true-secrets-nonprd-shared
  - group: true-network-uat
  - group: true-mq-uat
  - group: true-scale-down

  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/non-prod.yml
  - template: ../Templates/Variables/tags.yml

schedules:
  # M-F 3:00 AM (UTC + 5:30) India
  - cron: "30 20 * * *"
    displayName: Scaling Environment
    branches:
      include:
        - master

# set pr trigger to none to prevent daily build running against master branch changes
pr: none

trigger: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     vmImage: 'windows-latest'
    steps:
    - template: ../Templates/Build/build.yml
      parameters:
        db: 'true'
        certs: 'false'
        config: 'true'

- template: ../Templates/Stage/scale.deploy.yml
  parameters:
    scaleup: 'false'