steps:
  - powershell: |
      $guid=(New-Guid).Guid
      Write-Host "##vso[task.setvariable variable=deploymentsuffix]$guid"
    displayName: Set PID Name

  - task: AzurePowerShell@4
    displayName: Reporting Function App - Worker Count
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Reset-WebWorkerCount.ps1'
      ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "$(reportingFunctionAppName)"'
      azurePowerShellVersion: LatestVersion

  - task: AzureResourceGroupDeployment@2
    displayName: Reporting Function App - ARM
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      resourceGroupName: '${{ parameters.resourceGroupName }}'
      location: '${{ parameters.deployLocation }}'
      csmFile: '$(System.ArtifactsDirectory)/Drop/Templates/Function App/deploy.json'
      overrideParameters: '-pidDeploymentName "${{parameters.processJobId}}$(build.buildId)" -sku "$(functionAppSKU)" -logAnalyticsResourceId "$(logAnalyticsResourceId)" -functionAppName "$(reportingFunctionAppName)" -apphostingPlanName "$(appServicePlanNameReporting)"'
      deploymentName: '$(deploymentsuffix)'

  - task: AzurePowerShell@4
    displayName: Reporting Function App - Tags
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Add-Tags.ps1'
      ScriptArguments: '-tier "${{parameters.tier}}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "$(reportingFunctionAppName)"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - Diagnostics
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Add-DetailedErrorAndTraceLogging.ps1'
      ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "$(reportingFunctionAppName)"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - Set Build Variable
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Set-OutputVariable.ps1'
      ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}" -outputKeySuffix "Rep" -outputKeyName "ou_FunctionAppPrincipalId" -deploymentName "$(deploymentsuffix)"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - KV MSI
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Set-KeyVault-SecurityPermissions.ps1'
      ScriptArguments: '-vaultName "$(keyVault)" -targetObjectId "$(ou_FunctionAppPrincipalIdRep)" -resourceGroupName "${{ parameters.resourceGroupName }}"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - SQL MSI
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Add-SecurityGroupMember.ps1'
      ScriptArguments: '-groupObjectId "$(msiAdGroupObjectId)" -memberObjectId "$(ou_FunctionAppPrincipalIdRep)"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - SB MSI
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Add-RoleAssignmentMSI.ps1'
      ScriptArguments: '-resourceGroup "${{ parameters.resourceGroupName }}" -objectId "$(ou_FunctionAppPrincipalIdRep)" -resourceName "$(serviceBusNamespaceNameInt)" -roleDefinitionName "Azure Service Bus Data Sender" -resourceType "Microsoft.ServiceBus/Namespaces"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - Storage MSI
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Add-RoleAssignmentMSI.ps1'
      ScriptArguments: '-resourceGroup "${{ parameters.resourceGroupName }}" -objectId "$(ou_FunctionAppPrincipalIdRep)" -resourceName "$(storageAccountName)" -roleDefinitionName "Storage Blob Data Contributor" -resourceType "Microsoft.Storage/storageAccounts"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - Staging Slot
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Slots/Manage-Slots.ps1'
      ScriptArguments: '-action "CREATE" -slotName "STAGING" -appServicePlanName "$(appServicePlanNameReporting)" -resourceGroupName "${{ parameters.resourceGroupName }}" -appServiceName "$(reportingFunctionAppName)"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - App Settings
    inputs:
      azureSubscription: "${{ parameters.azureSubscriptionName }}"
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Set-AppSettings.ps1'
      ScriptArguments: '-slot "STAGING" -AppSettings @{"AzureWebJobsStorage"="${{ parameters.storageConnectionString }}";"WEBSITE_CONTENTAZUREFILECONNECTIONSTRING"="${{ parameters.storageConnectionString }}";"WEBSITE_CONTENTSHARE"="$(reportingFunctionAppName)";"FUNCTIONS_EXTENSION_VERSION"="~3";"WEBSITE_NODE_DEFAULT_VERSION"="8.11.1";"FUNCTIONS_WORKER_RUNTIME"="dotnet";"VaultName"="$(keyVault)";"APPINSIGHTS_INSTRUMENTATIONKEY"="${{ parameters.instrumentationKey }}";"IntegrationServiceBusConnectionString"="${{ parameters.serviceBusConnectionString }}";"IntegrationStorageConnectionString"="${{ parameters.storageConnectionString }}";"BeforeCutoffReportQueue"="$(beforeCutoffReportQueueName)";"OfficialInitialBalanceReportQueue"="$(officialInitialBalanceReportQueueName)";"OperativeBalanceReportQueue"="$(operativeBalanceReportQueueName)";"SapBalanceReportQueue"="$(sapBalanceReportQueueName)";"userRolesAndPermissionsReportQueue"="$(userRolesAndPermissionsReportQueueName)";"CommandTimeoutInSecs"="$(commandTimeoutInSecs)";"ReportPurgeInterval"="$(reportPurgeInterval)";} -resourceGroupName "${{ parameters.resourceGroupName }}" -webAppName "$(reportingFunctionAppName)"'
      azurePowerShellVersion: LatestVersion

  - task: AzurePowerShell@4
    displayName: Reporting Function App - Stop Staging Slot
    inputs:
      azureSubscription: '${{ parameters.azureSubscriptionName }}'
      ScriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Slots/Manage-Slots.ps1'
      ScriptArguments: '-action "STOP" -slotName "STAGING" -appServicePlanName "$(appServicePlanNameReporting)" -resourceGroupName "${{ parameters.resourceGroupName }}" -appServiceName "$(reportingFunctionAppName)"'
      azurePowerShellVersion: LatestVersion