steps:
 - task: AzureKeyVault@1
   displayName : Fetching KV Secrets
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     keyVaultName: "${{ parameters.keyVaultName}}"
     secretsFilter: "${{parameters.secretsFilter}}"