steps:
- script: echo '##vso[task.setvariable variable=env]${{parameters.env}}
  displayName: Set Environment

- task: DownloadBuildArtifacts@0
  displayName: Download Build Artifacts
  inputs:
    artifactName: Drop
    downloadPath: '$(System.ArtifactsDirectory)'

- template: ../Infra/fetchSecrets.yml
  parameters:
    azureSubscriptionName : '${{parameters.serviceConnection}}'
    keyVaultName: '$(keyVault)'
    secretsFilter: '*'

- script: echo '##vso[task.setvariable variable=Settings.VaultName]$(keyVaultAddress)
  displayName: Set Key Vault Address

- script: echo '##vso[task.setvariable variable=ApplicationInsights.InstrumentationKey]$(instrumentationkey)
  displayName: Set Instrumentation Key

- script: echo '##vso[task.setvariable variable=AzureAd.ClientId]$(uiAppClientId)
  displayName: Set Web Portal ClientId

- ${{ if eq(parameters['ui'], 'true') }}:
  - template: ./ui.deploy.yml
    parameters:
      serviceConnection : '${{parameters.serviceConnection}}'
      uiWebAppName : '$(appServiceNameUI)'
      downloadArtifacts : "false"

- template: ../Infra/flow.yml
  parameters:
    azureSubscriptionName :  '${{parameters.serviceConnection}}'