/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

IF EXISTS (Select 'X' from sys.schemas Where name = 'Admin')
BEGIN
	IF NOT EXISTS (SELECT 'X' FROM [Admin].[ControlScript] where Id='7b7af664-aac6-4737-b098-f5373876abac' AND Status = 1)
	BEGIN
		BEGIN TRY
			IF (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'Admin' AND  TABLE_NAME = 'OwnershipNode'))
			BEGIN
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=2
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=13
				UPDATE [Admin].[OwnershipNode] SET Status=2 WHERE OwnershipNodeId=14
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=15
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=18
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=19
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=20
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=21
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=28
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=29
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=30
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=31
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=32
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=33
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=34
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=35
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=36
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=37
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=38
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=39
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=40
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=41
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=42
				UPDATE [Admin].[OwnershipNode] SET Status=2 WHERE OwnershipNodeId=43
				UPDATE [Admin].[OwnershipNode] SET Status=2 WHERE OwnershipNodeId=44
				UPDATE [Admin].[OwnershipNode] SET Status=2 WHERE OwnershipNodeId=45
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=46
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=47
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=48
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=49
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=50
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=51
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=52
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=53
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=54
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=55
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=56
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=57
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=58
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=59
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=60
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=61
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=62
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=63
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=64
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=65
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=66
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=67
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=68
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=69
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=70
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=71
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=72
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=73
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=74
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=75
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=76
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=77
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=78
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=79
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=80
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=81
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=82
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=83
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=84
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=85
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=86
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=87
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=88
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=89
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=90
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=91
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=92
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=93
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=94
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=95
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=96
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=97
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=98
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=99
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=100
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=101
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=102
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=103
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=104
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=105
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=106
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=107
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=108
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=109
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=110
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=111
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=112
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=113
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=114
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=115
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=116
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=117
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=118
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=119
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=120
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=121
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=122
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=123
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=124
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=125
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=126
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=127
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=128
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=129
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=130
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=131
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=132
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=133
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=134
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=135
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=136
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=137
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=138
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=139
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=140
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=141
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=142
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=143
				UPDATE [Admin].[OwnershipNode] SET Status=2 WHERE OwnershipNodeId=144
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=145
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=146
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=147
				UPDATE [Admin].[OwnershipNode] SET Status=2 WHERE OwnershipNodeId=148
				UPDATE [Admin].[OwnershipNode] SET Status=2 WHERE OwnershipNodeId=149
				UPDATE [Admin].[OwnershipNode] SET Status=2 WHERE OwnershipNodeId=150
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=151
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=152
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=153
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=154
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=155
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=156
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=157
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=158
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=159
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=160
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=161
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=162
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=163
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=164
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=165
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=166
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=167
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=168
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=169
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=170
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=171
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=172
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=173
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=174
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=175
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=176
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=177
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=178
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=179
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=180
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=181
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=182
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=183
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=184
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=185
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=186
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=187
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=188
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=189
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=190
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=191
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=192
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=193
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=194
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=195
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=196
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=197
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=198
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=199
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=200
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=201
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=202
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=203
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=204
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=205
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=206
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=207
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=208
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=209
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=210
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=211
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=212
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=213
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=214
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=215
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=216
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=217
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=218
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=219
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=220
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=221
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=222
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=223
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=224
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=225
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=226
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=227
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=228
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=229
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=230
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=231
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=232
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=233
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=234
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=235
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=236
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=237
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=238
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=239
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=240
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=241
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=242
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=243
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=244
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=245
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=246
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=247
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=248
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=249
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=250
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=251
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=252
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=253
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=254
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=255
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=256
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=257
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=258
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=259
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=260
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=261
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=262
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=263
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=264
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=265
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=266
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=267
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=268
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=269
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=270
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=271
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=272
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=273
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=274
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=275
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=276
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=277
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=278
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=279
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=280
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=281
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=282
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=283
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=284
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=285
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=286
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=287
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=288
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=289
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=290
				UPDATE [Admin].[OwnershipNode] SET Status=1 WHERE OwnershipNodeId=291
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=292
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=293
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=294
				UPDATE [Admin].[OwnershipNode] SET Status=0 WHERE OwnershipNodeId=295
			END
			INSERT [Admin].[ControlScript] ([Id], [Status]) VALUES ('7b7af664-aac6-4737-b098-f5373876abac', 1);
		END TRY

		BEGIN CATCH
			INSERT [Admin].[ControlScript] ([Id], [Status]) VALUES ('7b7af664-aac6-4737-b098-f5373876abac', 0);
		END CATCH
	END
END