@sharedsteps=16581 @owner=jagudelos @ui @testplan=74716 @testsuite=74931 @MVP2and3 @S16.1
Feature: AdjustmentsToCutoffCalculations
	As a professional segment balance user, 
	I need the initial inventory logic to be 
	modified in the operational cut-off to discard 
	new events after the cut-off

Background: Login
	Given I am logged in as "profesional"

@bvt
Scenario: Verify initial inventory logic that is modified in the operational cut-off to discard new events after the cut-off
And I have "Excel" homologation data in the system
And I have uploaded inventories and movements into system
And I navigate to "Operational Cutoff" page
And I perform cutoff for segment without registered intial inventories
Then use the value "0" for operational cut-off calculations as there are no inventories as is currently done
And inventories with a value of "0" should not be created
And use "0" as initial inventory value
When I have initial inventory per product has a single event recorded without cut-off ticket
And I perform cutoff for segment with single event
Then initial inventory should be sum of the inventories of a product correspoding to day before the balance start date
When I have initial inventory per product have multiple events recorded without cut-off ticket
And I perform cutoff for segment with multiple events without cutoff ticket
Then initial inventory should be sum of the inventories of a product correspoding to day before the balance start date
When I have initial inventory per product has a single event recorded with cut-off ticket
And I perform cutoff for segment with single event
Then initial inventory should be sum of the inventories of a product correspoding to day before the balance start date and that have cutoff ticket
When I have initial inventory per product have multiple events recorded with cut-off ticket
And I perform cutoff for segment with multiple events with cutoff ticket
Then initial inventory should be sum of the inventories of a product correspoding to day before the balance start date and that have a successfully executed cut-off ticket

@manual
Scenario: Verify initial logic when processing cutoff is failed
And I have "Excel" homologation data in the system
And I have uploaded inventories and movements into system
When I navigate to "Operational Cutoff" page
And I perform cutoff for segment 
But processing ends in a failure
Then reverse all the changes made 
And the movements generated by TRUE must be eliminated
And no record of the previously executed successful operational cut-off can be left without a ticket number when performing the failed process rollback

@manual
Scenario: Verify pending records are considered in Operative delta
And I have "Excel" homologation data in the system
And I have uploaded inventories and movements into system
When I navigate to "Operational Cutoff" page
And I perform cutoff for segment
And I have uploaded updated records into the system
And I perform operative delta for same segment
Then these pending records should be considered in operative delta


@manual
Scenario: Verify pending records should not be processed in successive operational cut-offs/operational cut-off report/report with ownership/FICO for ownership determination
And I have "Excel" homologation data in the system
And I have uploaded inventories and movements into system
When I navigate to "Operational Cutoff" page
And I perform cutoff for segment
And processing of cutoff started and ended successfully
Then do not use pending records in successive operational cut-offs
And do not display pending records in the operational cut-off report
And do not display pending records in the report with ownership
And do not send pending records to FICO for ownership determination