@sharedsteps=4013 @owner=jagudelos @ui @testplan=43714 @testsuite=43716 @prodready1.5
Feature: ExecuteTheFirstOwnershipCalculationProcessOfNode
As TRUE system, I need to send to FICO the owners of the inventories
reported by the business systems to execute the first ownership
calculation process of a node.

Background: Login
Given  I am logged in as "admin"

@testcase=52334 @version=2
Scenario: Verify initial inventory collection that sent to FICO when there is no ownership for initial inventories from both owner and ownership tables
And TRUE system is preparing the initial inventories data that send them to FICO
When there is no ownership for initial inventories from both owner and ownership tables
And generate ownership ticket without initial inventories
Then send initial inventories collection "without" data to FICO

@testcase=52335
Scenario: _01Verify initial inventory collection that sent to FICO when there is ownership for initial inventories sent by source systems
And TRUE system is preparing the initial inventories data that send them to FICO
When there are inventories of day before ticket calculation generated by source system from owner table
And there are no inventories for ownership calculation by application from ownership table
And generate ownership ticket with initial inventories
Then send initial inventories collection "with" data to FICO
When unit of ownership that corresponds to owner is percentage
Then send net volume to FICO should be calculated as volume of the product multiplied by percentage that corresponds to owner and result should be divided by 100
When unit of ownership that corresponds to owner is other than percenatge
Then send owner value to FICO

@testcase=52336
Scenario: _02Verify initial inventories collection that sent to FICO when there is ownership for initial inventories calculated through the application
And I have a segment details where ownership is already calculated
When there are no inventories for ownership calculation by source system from owner table
And there are inventories of day before ticket calculation generated by application from ownership table
And generate ownership ticket with initial inventories from ownership table
Then send initial inventory collection to FICO with the data calculated through the application
@testcase=52337
Scenario: _03Verify initial inventory collection that sent to FICO when an inventory has ownership sent by source system and also ownership calculated by application
And I have a segment details where ownership is already calculated
When there is an inventory where ownership sent by source system and ownership calculated by application
Then send to FICO only the ownership data calculated through the ownership functionality of the application

@testcase=52338
Scenario: Verify initial inventory collection that sent to FICO when there is ownership for initial inventories calculated through source system and application
And TRUE system is preparing the initial inventories data that send them to FICO
And there are inventories of day before ticket calculation generated by source system from owner table
And there are no inventories for ownership calculation by application from ownership table
And generate ownership ticket with initial inventories
When there are inventories generated by source system on day before ticket calculation from owner table
And there are inventories of day before ticket calculation generated by application from ownership table
And generate ownership ticket with initial inventories from both owner and ownership table
Then send initial inventories collection with data to FICO that is generated by source system from owner table
When unit of ownership that corresponds to owner is percentage
Then send net volume to FICO should be calculated as volume of the product multiplied by percentage that corresponds to owner and result should be divided by 100
When unit of ownership that corresponds to owner is other than percenatge
Then send owner value to FICO
And add initial inventory collection that send to FICO with the data calculated through the application

@testcase=52339 
Scenario: Verify TRUE sends FICO inventory ownership records reported by source systems and FICO returns a successful response
And TRUE system is preparing the initial inventories data that send them to FICO
And the system is processing the FICO service response
When TRUE sends to FICO ownership data of inventories reported by the source systems
And FICO returns successful response
And "movimientosErrores" and "inventariosErrores" collections do not have data
And there are objects in any of the collections "resultadoMovimientos" or "resultadoInventarios"
Then store the ownership of initial inventories sent to FICO reported by source system in the table that supports the ownership functionality of the application
And assign each ownership record the corresponding ticket number
And each ownership record must have the rule name "Propiedad desde la fuente" and version should be 1
