@sharedsteps=4013 @owner=jagudelos @testsuite=39227 @testplan=39221 @ui @parallel=false
Feature: IncludeFicoTheInformationOfEventsContractsAndCancellationMovements
In order to record purchase / sale / self-consumption / Loans movements
As a TRUE System
I need to process the ownership information generated by FICO

Background: Login
	Given I am logged in as "admin"

@version=2 @testcase=41406 @bvt1.5
Scenario:Verify that system send the information of the planning, programming and collaboration agreements events found to FICO.
	And I have ownershipcalculation for segment with events information for same segment within the Range of OwnershipCalculation date
	Then Verify that System should send the information details to the FICO "with" Data
	And Verify that system should send the events details in the "eventos" array of FICO Collection

@version=2 @testcase=41407
Scenario:Verify that when there are no Events information during ownership calculation, system should not send the data to FICO.
	And I have ownershipcalculation for segment which did not have events information for same segment within the Range of OwnershipCalculation date
	Then Verify that System should send the information details to the FICO "without" Data
	And Verify that "eventos" array of FICO Collection should not contains any data

@version=2 @testcase=41408
Scenario:Verify that Events information should not be sending the data to FICO when start and end date are not within the Range of OwnershipCalculation date.
	And I have events information for segment with Movements and inventories but not within the range of OwnershipCalculation date
	Then Verify that System should send the information details to the FICO "without" Data
	And Verify that "eventos" array of FICO Collection should not contains any data

@version=2 @testcase=41409 @bvt1.5
Scenario:Verify that system send the information of the contracts found to FICO.
	And I have ownershipcalculation for segment and SalesAndPurchase information for same segment within the Range of OwnershipCalculation date
	Then Verify that System should send the information details to the FICO "with" Data
	And Verify that system should send the contracts details in the "movimientosComerciales" array of FICO Collection

@version=2 @testcase=41410
Scenario:Verify that when there are no contracts information during ownership calculation, system should not send the data to FICO.
	And I have ownershipcalculation for segment and did not have SalesAndPurchase information for same segment within the Range of OwnershipCalculation date
	Then Verify that System should send the information details to the FICO "without" Data
	And Verify that "eventos" array of FICO Collection should not contains any data

@version=2 @testcase=41411
Scenario:Verify that Contrancts information should not be sending the data to FICO when start and end date are not within the Range of OwnershipCalculation date.
	And I have SalesAndPurchase information for segment but not within the range of OwnershipCalculation date
	Then Verify that System should send the information details to the FICO "without" Data
	And Verify that "movimientosComerciales" array of FICO Collection should not contains any data

@version=3 @testcase=41412 @bvt1.5
Scenario Outline:Verify that system should send ownership percentage to FICO if the variables assigned for ownership strategies configured at Node-Product level set to 1.
	And I have "ownershipnodes" created
	And I have ownership strategy for node
	And I have ownership strategy for node products
	And I have ownership strategy for node connections
	And Variable data for node storage location for which "<field>" value is set to True
	When I navigate to "Operational Cutoff" page
	And I click on "NewCut" "button"
	And I choose CategoryElement from "InitTicket" "Segment" "combobox"
	And I select the FinalDate lessthan "4" days from CurrentDate on "Cutoff" DatePicker
	And I click on "InitTicket" "submit" "button"
	And I change the elements count per page to 50
	And I select all pending records from grid
	And I click on "ErrorsGrid" "AddNote" "button"
	And I enter valid value into "AddComment" "Comment" "textbox"
	And I click on "AddComment" "Submit" "button"
	And validate that "ErrorsGrid" "Submit" "button" as enabled
	And I click on "ErrorsGrid" "Submit" "button"
	And I change the elements count per page to 50
	And I select all unbalances in the grid
	And I click on "consistencyCheck" "AddNote" "button"
	And I enter valid value into "AddComment" "Comment" "textbox"
	And I click on "AddComment" "submit" "button"
	And I click on "unbalancesGrid" "submit" "button"
	And I click on "ConfirmCutoff" "Submit" "button"
	And I wait till cutoff ticket processing to complete
	And I navigate to "Ownershipcalculation" page
	And I click on "NewBalance" "button"
	And I select segment from "OwnershipCal" "Segment" "dropdown"
	And I select the FinalDate lessthan "1" days from CurrentDate on "Ownership" DatePicker
	And I click on "ownershipCalculationCriteria" "Submit" "button"
	Then I see "Todos los nodos tienen configurada una estrategia de propiedad." message for "Nodos con estrategia de propiedad"
	And I verify all "9" validations passed
	And I click on "ownershipCalulationValidations" "Submit" "button"
	And I click on "ownershipCalculationConfirmation" "Submit" "button"
	And verify the ownership is calculated successfully
	And Verify that System should send the information details to the FICO "with" Data
	And Verify that system should send the ownership percentage details within "<collectionObject>" object in "configuracionNodo" array of FICO Collection

	Examples:
		| field      | collectionObject |
		| PI         | pi               |
		| PNI        | pni              |
		| INTERFASE  | interfase        |
		| TOLERANCIA | tolerancia       |
		| INVENTARIO | inventarioFinal  |

@version=3 @testcase=41413
Scenario Outline:Verify that system should send 0 to FICO if the variables assigned for ownership strategies configured at Node-Product level set to 0.
	And I have "ownershipnodes" created
	And I have ownership strategy for node
	And I have ownership strategy for node products
	And I have ownership strategy for node connections
	When I navigate to "Operational Cutoff" page
	And I click on "NewCut" "button"
	And I choose CategoryElement from "InitTicket" "Segment" "combobox"
	And I select the FinalDate lessthan "4" days from CurrentDate on "Cutoff" DatePicker
	And I click on "InitTicket" "submit" "button"
	And I change the elements count per page to 50
	And I select all pending records from grid
	And I click on "ErrorsGrid" "AddNote" "button"
	And I enter valid value into "AddComment" "Comment" "textbox"
	And I click on "AddComment" "Submit" "button"
	And validate that "ErrorsGrid" "Submit" "button" as enabled
	And I click on "ErrorsGrid" "Submit" "button"
	And I change the elements count per page to 50
	And I select all unbalances in the grid
	And I click on "consistencyCheck" "AddNote" "button"
	And I enter valid value into "AddComment" "Comment" "textbox"
	And I click on "AddComment" "submit" "button"
	And I click on "unbalancesGrid" "submit" "button"
	And I click on "ConfirmCutoff" "Submit" "button"
	And I wait till cutoff ticket processing to complete
	And I navigate to "Ownershipcalculation" page
	And I click on "NewBalance" "button"
	And I select segment from "OwnershipCal" "Segment" "dropdown"
	And I select the FinalDate lessthan "1" days from CurrentDate on "Ownership" DatePicker
	And I click on "ownershipCalculationCriteria" "Submit" "button"
	Then I see "Todos los nodos tienen configurada una estrategia de propiedad." message for "Nodos con estrategia de propiedad"
	And I verify all "9" validations passed
	And I click on "ownershipCalulationValidations" "Submit" "button"
	And I click on "ownershipCalculationConfirmation" "Submit" "button"
	Then verify the ownership is calculated successfully
	Then Verify that System should send the information details to the FICO "without" Data
	And Verify that system should send null details within "<collectionObject>" object in "configuracionNodo" array of FICO Collection

	Examples:
		| field      | collectionObject |
		| PI         | pi               |
		| PNI        | pni              |
		| INTERFASE  | interfase        |
		| TOLERANCIA | tolerancia       |
		| INVENTARIO | inventarioFinal  |

@version=2 @testcase=41414
Scenario:Validate that system should not sent any cancellation movements to FICO if user create new cancellation Movement from Ownership edition page for evacuation type
	And I have movements of the evacuation type registered the day before the day of the period being executed through FICO Service Response
	And I have ownership calculation data generated in the system
	Then Verify that System should send the information details to the FICO "without" Data
	And Verify that system should not sent data in "movimientos" array of FICO Collection

@version=2 @testcase=41415 @bvt1.5
Scenario:Validate that system should sent the cancellation movements to FICO when there are movements of the evacuation type which have not been canceled
	And I have movements of the evacuation type registered the day before the day of the period being executed through FICO Service Response
	And I have ownership calculation data generated in the system
	Then Verify that System should send the information details to the FICO "with" Data
	And System should generates and temporarily stores the cancellation movements to send them FICO with movement type as "Anulación Entrada" and "Anulación Salida"
	And Verify that system should add the new cancellation movements generated for the day of the period in movements array of FICO Collection for "Anulación Entrada" and "Anulación Salida"

@version=2 @testcase=41416
Scenario:Validate that system should sent the cancellation movements to FICO when there are movements of the evacuation registered through both service response and UI
	And I have "ownershipnodes" created
	And Ownership is Calculated for Segment and Ticket is Generated
	And I have movements of the evacuation type registered the day before the day of the period being executed through FICO Service Response
	And I have created a new cancellation movements through the ownership edition page with Annuluation movement type
	Then Verify that System should send the information details to the FICO "with" Data
	And System should generates and temporarily stores the cancellation movements for both the movements registered through service and UI to send them FICO with movement type as "Anulación Entrada" and "Anulación Salida"
	And Verify that system should add the new cancellation movements generated for the day of the period in movements array of FICO Collection for "Anulación Entrada" and "Anulación Salida"

@version=2 @testcase=41417 @bvt1.5
Scenario: Verify the functionality when service return data in the "resultadoMovimientosComerciales" object of FICO collection
	And I have ownershipcalculation for segment and SalesAndPurchase information for same segment within the Range of OwnershipCalculation date
	And Verify that System should send the information details to the FICO "with" Data
	When the service returns data in "resultadoMovimientosComercial" collection
	Then system should register the new contract movements with ownership details
	And Verify that source system value should be FICO
	And Verify that the the movements must be assigned to the ownership ticket generated for the day of the period
	And Verify that net volume must be equal to the value volumen returned by FICO
	And Verify that source node for new movement should be equal to the Destination Node of original Movement for Movement Types
	And Verify that the source product type for new movement should be equal to the destination product of original Movement for Movement Types

@version=2 @testcase=41418 @bvt1.5
Scenario: Verify the functionality when service return data in the "movimientosNuevos" object of FICO collection when "tipoAcuerdo" is equal to "COLABORACION"
	And I have ownershipcalculation for segment with events information for same segment within the Range of OwnershipCalculation date
	And Verify that System should send the information details to the FICO "with" Data
	When the service returns data in "movimientosNuevos" collection
	And the value of the field "tipoAcuerdo" is equal to "COLABORACION"
	Then system should register the new movements with ownership details
	And Verify that source system value should be FICO for Collaboracion Movements
	And Verify that the the movements must be assigned to the ownership ticket generated for the day of the period for Collaboracion Movements
	And Verify that net volume must be equal to the value volumenPropiedad returned by FICO for Collaboracion Movements
	And Verify that source node for new movement should be equal to the Destination Node of original Movement for Collaboracion Movement Types
	And Verify that the source product type for new movement should be equal to the destination product of original Movement for Collaboracion Movement Types

@version=2 @testcase=41419
Scenario: Verify the functionality when service return data in the "movimientosNuevos" object of FICO collection when "tipoAcuerdo" is equal to "EVACUACION"
	And I have ownershipcalculation for segment with events information for same segment within the Range of OwnershipCalculation date
	And Verify that System should send the information details to the FICO "with" Data
	When the service returns data in "movimientosNuevos" collection
	And the value of the field "tipoAcuerdo" is equal to "EVACUACION"
	Then system should register the new movements with ownership details for Evacuation Movements
	And Verify that source system value should be FICO
	And Verify that the the movements must be assigned to the ownership ticket generated for the day of the period for Evacuation Movements
	And Verify that net volume must be equal to the value volumenPropiedad returned by FICO
	And Verify that source node for new movement should be equal to the Destination Node of original Movement for Evacuation Movement Types
	And Verify that the source product type for new movement should be equal to the destination product of original Movement for Evacuation Movement Types

@version=3 @testcase=41420 @bvt1.5
Scenario: Verify the process of ownership calculation results when one or both of the FICO collection empty
	And I have "ownershipnodes" created
	And I have ownership strategy for node
	And I have ownership strategy for node products
	And I have ownership strategy for node connections
	When I navigate to "Operational Cutoff" page
	And I click on "NewCut" "button"
	And I choose CategoryElement from "InitTicket" "Segment" "combobox"
	And I select the FinalDate lessthan "4" days from CurrentDate on "Cutoff" DatePicker
	And I click on "InitTicket" "submit" "button"
	And I change the elements count per page to 50
	And I select all pending records from grid
	And I click on "ErrorsGrid" "AddNote" "button"
	And I enter valid value into "AddComment" "Comment" "textbox"
	And I click on "AddComment" "Submit" "button"
	And validate that "ErrorsGrid" "Submit" "button" as enabled
	And I click on "ErrorsGrid" "Submit" "button"
	And I change the elements count per page to 50
	And I select all unbalances in the grid
	And I click on "consistencyCheck" "AddNote" "button"
	And I enter valid value into "AddComment" "Comment" "textbox"
	And I click on "AddComment" "submit" "button"
	And I click on "unbalancesGrid" "submit" "button"
	And I click on "ConfirmCutoff" "Submit" "button"
	And I wait till cutoff ticket processing to complete
	And I navigate to "Ownershipcalculation" page
	And I click on "NewBalance" "button"
	And I select segment from "OwnershipCal" "Segment" "dropdown"
	And I select the FinalDate lessthan "1" days from CurrentDate on "Ownership" DatePicker
	And I click on "ownershipCalculationCriteria" "Submit" "button"
	Then I see "Todos los nodos tienen configurada una estrategia de propiedad." message for "Nodos con estrategia de propiedad"
	And I verify all "9" validations passed
	And I click on "ownershipCalulationValidations" "Submit" "button"
	And I click on "ownershipCalculationConfirmation" "Submit" "button"
	Then verify the ownership is calculated successfully
	And Verify that System should send the information details to the FICO "with" Data
	And the service returns empty data one or both of the collection

@manual @version=3 @testcase=41421
Scenario: Validate that FICO doesn't returns the ownership of movements and inventories that are sent as movements in request and as input movements
	And I have "InputMovementsWithOwnership" created
	And System add the ownership details for the generated movements in "movimientos" array of FICO Collection
	When I generate the operational cutoff
	And I navigate to "OwnershipDeterminationBySegmnet" page
	And I click on "NewBalance" "button"
	And I select segment from "OwnershipCal" "Segment" "dropdown"
	And I select the FinalDate lessthan "1" days from CurrentDate on "Ownership" DatePicker
	And I click on "ownershipCalculationCriteria" "Submit" "button"
	And I verify all validations passed
	And I click on "ownershipCalulationValidations" "Submit" "button"
	And I click on "ownershipCalculationConfirmation" "Submit" "button"
	Then validate tickets generated for "4" days in "tickets" "grid" of the "segment"
	And validate tickets are processing day by day and ends in "Propiedad" state
	And verify that FICO service should not returned the ownership of movements and inventories

@manual @version=3 @testcase=41422
Scenario: Validate that FICO doesn't returns the ownership of movements and inventories for movement type Anulación Entrada and Anulación Salida
	And I have "NodesWithOwnershipButMovementswithoutOwnership" created
	And I have movements and inventories of movement type Anulación Entrada and Anulación Salida in excel
	When I generate the operational cutoff
	And I navigate to "OwnershipDeterminationBySegmnet" page
	And I click on "NewBalance" "button"
	And I select segment from "OwnershipCal" "Segment" "dropdown"
	And I select the FinalDate lessthan "1" days from CurrentDate on "Ownership" DatePicker
	And I click on "ownershipCalculationCriteria" "Submit" "button"
	And I verify all validations passed
	And I click on "ownershipCalulationValidations" "Submit" "button"
	And I click on "ownershipCalculationConfirmation" "Submit" "button"
	Then validate tickets generated for "4" days in "tickets" "grid" of the "segment"
	And validate tickets are processing day by day and ends in "Propiedad" state
	And verify that FICO service should not returned the ownership of movements and inventories for input movements and movements sent with request

@manual @version=3 @testcase=41423
Scenario: Validate ticket of the period in failed state
	And I have "MovementsandNodesWithoutOwnership" created
	When I generate the operational cutoff
	And I navigate to "OwnershipDeterminationBySegmnet" page
	And I click on "NewBalance" "button"
	And I select segment from "OwnershipCal" "Segment" "dropdown"
	And I select the FinalDate lessthan "1" days from CurrentDate on "Ownership" DatePicker
	And I click on "ownershipCalculationCriteria" "Submit" "button"
	And I verify all validations passed
	And I click on "ownershipCalulationValidations" "Submit" "button"
	And I click on "ownershipCalculationConfirmation" "Submit" "button"
	And validate tickets generated for "4" days in "tickets" "grid" of the "segment"
	And validate first ticket in "Fallido" state
	And validate subsequent tickets are processing day by day and ends in "Fallido" state
	Then validate the error message "El motor de reglas no está retornando la propiedad de todos los movimientos e inventarios del día del periodo."
	And validate ticketnumber correspond to the ticketnumber generated for the destination node on the day are in "Fallido" state