variables:
  - group: true-threshold
  - group: true-secrets-nonprd-shared
  - group: true-secrets-dev
  - group: true-network-dev
  - group: true-automation
  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/non-prod.yml

trigger: none
pr: none

stages:
- template: ../Templates/Stage/app.build.yml
- template: ../Templates/Stage/app.deploy.yml
  parameters:
    canExecuteAutomation: '$(dev)'
    automation: 'true'
- template: ../Templates/Stage/app.purge.yml