variables:
    - group: true-threshold
    - group: true-secrets-nonprd-shared
    - group: true-secrets-dev
    - group: true-network-dev
    - group: true-mq-dev
    - template: ../Templates/Variables/package.yml
    - template: ../Templates/Variables/infra.yml
    - template: ../Templates/Variables/non-prod.yml
  
trigger: none
pr: none
  
stages:
- template: ../Templates/Stage/db.build.yml
- template: ../Templates/Stage/db.backup.yml
  parameters:
    dbBackUp: 'true'
    offshoreChanges: "$(offshoreChanges)"