variables:
  - group: true-secrets-dev
  - group: true-secrets-nonprd-shared
  - group: true-network-dev
  
  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/non-prod.yml
  - template: ../Templates/Variables/tags.yml

trigger: none
pr: none

stages:
- stage: Build
  jobs:
  - job: Package
    pool:
     vmImage: 'windows-latest'
    steps:
     - template: ../../Templates/Build/build.yml
       parameters:
         app: 'true'

     - template: ../Templates/package.yml
       parameters:
         infra: 'true'

- stage: Deploy
  jobs:
  - deployment: Deploy
    pool:
     vmImage: 'windows-latest'
    environment: $(env)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: Drop
              downloadPath: '$(System.ArtifactsDirectory)'
    
          - task: AzureRmWebAppDeployment@4
            displayName: Function App - Deadletter
            inputs:
              azureSubscription: '$(serviceConnection)'
              WebAppName: '$(dlFunctionAppName)'
              deployToSlotOrASE: true
              ResourceGroupName: '$(resourceGroupName)'
              SlotName: 'STAGING'
              packageForLinux: '$(System.ArtifactsDirectory)/Drop/Ecp.True.Host.Functions.Deadletter.zip'

          - template: ../Templates/Infra/Swap/deadletter.yml
            parameters:
              serviceConnection: $(serviceConnection)
              env: '$(env)'

          - task: AzureCLI@2
            displayName: Remove Sinoper Deadletter Functions Settings
            inputs:
              azureSubscription: '$(serviceConnection)'
              scriptType: ps
              scriptPath: '$(System.ArtifactsDirectory)/Drop/Scripts/Remove-SinoperFunctions.ps1'
              arguments: '-functionAppName "$(dlFunctionAppName)" -resourceGroupName "$(resourceGroupName)"'