variables:
  - group: true-secrets-dev
  - group: true-release-threshold
  - group: true-secrets-nonprd-shared
  - group: true-network-dev
  - group: true-mq-dev
  - group: true-scale-down

  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/non-prod.yml
  - template: ../Templates/Variables/tags.yml

# set pr trigger to none to prevent daily build running against master branch changes
pr: none

trigger: none

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
     vmImage: 'windows-latest'
    steps:
    - template: ../Templates/Build/build.yml
      parameters:
        db: 'true'
        certs: 'false'
        config: 'true'

- template: ../Templates/Stage/scale.deploy.yml
  parameters:
    scaleup: 'false'