variables:
  - group: true-secrets-dev
  - group: true-secrets-nonprd-shared
  - group: true-network-dev
  - template: ../Templates/Variables/package.yml
  - template: ../Templates/Variables/infra.yml
  - template: ../Templates/Variables/non-prod.yml
  - template: ../Templates/Variables/tags.yml
  - name: aksAgentPoolVmSize
    value: 'Standard_D4s_v3'

trigger: none
pr: none

stages:
- template: ../Templates/Stage/infra.build.yml
- template: ../Templates/Stage/infra.shared.deploy.yml