parameters:
- name: env
  type: string
  values: 
  - 'dev-app'
  - 'uat-app'
  - 'qas-app'
  - 'stg-app'
  - 'prd-app'
  default: 'dev-app'
- name: status
  type: string
  values:
  - 'Sent'
  - 'Ownership'
  - 'Failed'
  - 'Locked'
  - 'Unlocked'
  - 'Publishing'
  - 'Published'
  - 'Submit for approval'
  - 'Approved'
  - 'Rejected'
  - 'Reopened'
  - 'Deltas'
  default: 'Sent'

variables:
  - name: statusId
    ${{ if eq(parameters.status, 'Sent') }}:
      value: 1
    ${{ if eq(parameters.status, 'Ownership') }}:
      value: 2
    ${{ if eq(parameters.status, 'Failed') }}:
      value: 3
    ${{ if eq(parameters.status, 'Locked') }}:
      value: 4
    ${{ if eq(parameters.status, 'Unlocked') }}:
      value: 5
    ${{ if eq(parameters.status, 'Publishing') }}:
      value: 6
    ${{ if eq(parameters.status, 'Published') }}:
      value: 7
    ${{ if eq(parameters.status, 'Submit for approval') }}:
      value: 8
    ${{ if eq(parameters.status, 'Approved') }}:
      value: 9
    ${{ if eq(parameters.status, 'Rejected') }}:
      value: 10
    ${{ if eq(parameters.status, 'Reopened') }}:
      value: 11
    ${{ if eq(parameters.status, 'Deltas') }}:
      value: 12
  - ${{ if eq(parameters.env, 'dev-app') }}:
    - group: true-secrets-dev
  - ${{ if eq(parameters.env, 'uat-app') }}:
    - group: true-secrets-uat
  - ${{ if eq(parameters.env, 'stg-app') }}:
    - group: true-secrets-stg
  - ${{ if eq(parameters.env, 'qas-app') }}:
    - group: true-secrets-qas
  - ${{ if eq(parameters.env, 'prd-app') }}:
    - group: true-secrets-prd

jobs:
  - deployment: Run

    pool:
      vmImage: ubuntu-latest
    environment: ${{ parameters.env }}

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: PowerShell@2
              inputs:
                filePath: '$(Build.SourcesDirectory)/Deploy/Scripts/Update-NodeStatus.ps1'
                arguments: '-SqlServerConnectionString "$(sqlconnectionstring)" -ticketId $(ticketId) -statusId $(statusId) -nodeName "$(nodeName)"'
                failOnStderr: true
                showWarnings: true
                pwsh: true
  