@sharedsteps=7539 @owner=jagudelos @api @testplan=55104 @testsuite=55111
Feature: InformSapPoTheResultsOfTheProcessingOfMovementsOrInventories
As TRUE system, I need to invoke a SAP PO Web API to inform what was
the result of an processing ID sent previously

Background: Login
Given I am authenticated as "admin"

@testcase=57627 @version=2 @bvt
Scenario: Verify process identifier is stored when TRUE system receives a request through the inventory Web APIs exposed for SAP PO
Given that the TRUE system receives a request through the "Inventories" Web APIs exposed for SAP PO
When TRUE system generates the process identifier
Then store the process identifier
And the date time of receipt of the information

@testcase=57628 @version=2 @bvt
Scenario: Verify process identifier is stored when TRUE system receives a request through the movement Web APIs exposed for SAP PO
Given that the TRUE system receives a request through the "Movements" Web APIs exposed for SAP PO
When TRUE system generates the process identifier
Then store the process identifier
And the date time of receipt of the information

@testcase=57629 @version=2 @bvt
Scenario: Verify inventories successfully registered with process identifier
Given that the TRUE system receives "Inventories" through the Web API exposed to SAP PO
When TRUE system successfully stores "inventories" information
Then each inventory must have assigned the process identifier returned to SAP PO

@testcase=57630 @version=2 @bvt
Scenario: Verify movements successfully registered with process identifier
Given that the TRUE system receives "Movements" through the Web API exposed to SAP PO
When TRUE system successfully stores "movements" information
Then each movement must have assigned the process identifier returned to SAP PO

@testcase=57631 @version=2
Scenario: Verify process identifier is assigned When errors are generated during inventories validations
Given that the TRUE system receives "Inventories" with errors through the Web API exposed to SAP PO
When errors are generated during inventories validations
Then each message in the pending transaction log must have assigned the process identifier returned to SAP PO

@testcase=57632 @version=2
Scenario: Verify process identifier is assigned When errors are generated during movements validations
Given that the TRUE system receives "Movements" with errors through the Web API exposed to SAP PO
When errors are generated during movements validations
Then each message in the pending transaction log must have assigned the process identifier returned to SAP PO

@testcase=57633 @version=2 @bvt
Scenario: Verify the results report of inventories when one inventory is processed successfully to SAP PO
Given that the TRUE system is processing the "Inventories" received through the Web API exposed to SAP PO
When the TRUE system finishes the "inventories" processing of a process identifier
Then result report should send "processId" as process identifier
And "documentId" field should have "inventory" identifier
And "transactionId" field should have inventory identifier generated by TRUE
And "errorCode" field should have "0000"
And "errorDsc" field should have "Transacción exitosa"

@testcase=57634 @version=2
Scenario: Verify the results report of inventories when two inventories are processed successfully to SAP PO
Given that the TRUE system is processing 2 "Inventories" received through the Web API exposed to SAP PO
When the TRUE system finishes the "inventories" processing of a process identifier
Then result report should send "processId" as process identifier
And "documents" collection should have two objects with required details

@testcase=57635 @version=2 @bvt
Scenario: Verify the results report of inventories when one inventory is not processed successfully to SAP PO and having single error
Given that the TRUE system receives "Inventories" with errors through the Web API exposed to SAP PO
When the TRUE system finishes the inventories processing of a process identifier with error
Then result report should send "processId" as process identifier
And "documentId" field should have "inventory" identifier
And "transactionId" field should have empty
And "errorCode" field should have code generated by TRUE
And "errorDsc" field should have error registered by TRUE

@testcase=57636 @version=2
Scenario: Verify the results report of inventories when one inventory is not processed successfully to SAP PO and having two errors
Given that the TRUE system is processing the "Inventories" received through the Web API exposed to SAP PO
When the TRUE system finishes the inventories processing of a process identifier with error
Then result report should send "processId" as process identifier
And "documentId" field should have "inventory" identifier
And "transactionId" field should have empty
And "errors" collection should have two objects with errorCode and errorDsc

@testcase=57637 @version=2 @bvt
Scenario: Verify the results report of movements when one movement is processed successfully to SAP PO
Given that the TRUE system is processing the "Movements" received through the Web API exposed to SAP PO
When the TRUE system finishes the "movements" processing of a process identifier
Then result report should send "processId" as process identifier
And "documentId" field should have "movement" identifier
And "transactionId" field should have movement identifier generated by TRUE
And "errorCode" field should have "0000"
And "errorDsc" field should have "Transacción exitosa"

@testcase=57638 @version=2
Scenario: Verify the results report of movements when two movements are processed successfully to SAP PO
Given that the TRUE system is processing 2 "Movements" received through the Web API exposed to SAP PO
When the TRUE system finishes the "movements" processing of a process identifier
Then result report should send "processId" as process identifier
And "documents" collection should have two objects with required details

@testcase=57639 @version=2
Scenario: Verify the results report of movements when one movement is not processed successfully to SAP PO and having single error
Given that the TRUE system is processing the "Movements" received through the Web API exposed to SAP PO
When the TRUE system finishes the movements processing of a process identifier with error
Then result report should send "processId" as process identifier
And "documentId" field should have "movement" identifier
And "transactionId" field should have empty
And "errorCode" field should have code generated by TRUE
And "errorDsc" field should have error registered by TRUE

@testcase=57640 @version=2
Scenario: Verify the results report of movements when one movement is not processed successfully to SAP PO and having two errors
Given that the TRUE system is processing the "Movements" received through the Web API exposed to SAP PO
When the TRUE system finishes the movements processing of a process identifier with error
Then result report should send "processId" as process identifier
And "documentId" field should have "movements" identifier
And "transactionId" field should have empty
And "errors" collection should have two objects with errorCode and errorDsc

@testcase=57641 @manual
Scenario: Verify successful submission of inventory results to SAP PO
Given that the TRUE system consumes the SAP PO Web API to send the results of a "inventory" process identifier
When SAP PO Web API response is successful
Then update to send to SAP PO the process status in SapTracking table
And store the system date time to have the sending traceability of the SAP PO response in SapTracking table
Then update to send to SAP PO the process status
And store the system date time to have the sending traceability of the SAP PO response

@testcase=57642 @manual
Scenario: Verify successful submission of movement results to SAP PO
Given that the TRUE system consumes the SAP PO Web API to send the results of a "movement" process identifier
When SAP PO Web API response is successful
Then update to send to SAP PO the process status in SapTracking table
And store the system date time to have the sending traceability of the SAP PO response in SapTracking table

@testcase=57643 @manual
Scenario: Verify failed submission of inventory results to SAP PO
Given that the TRUE system consumes the SAP PO Web API to send the results of a "inventory" process identifier
When SAP PO Web API response is failed
Then system must retry until 6 times the information sending
And even sixth attempt is failed then update the status of the process identifier to failed
And store the system date time to have the sending traceability of the SAP PO response in SapTracking table
And the exception returned by SAP PO must be stored in application insights

@testcase=57644 @manual
Scenario: Verify failed submission of inventory results to SAP PO and succeeded while retries
Given that the TRUE system consumes the SAP PO Web API to send the results of a "inventory" process identifier
When SAP PO Web API response is failed
And system must retry until 6 times the information sending
And while retry the status of the process identifier is succeeded
Then update to send to SAP PO the process status in SapTracking table
And store the system date time to have the sending traceability of the SAP PO response in SapTracking table

@testcase=57645 @manual
Scenario: Verify failed submission of movement results to SAP PO
Given that the TRUE system consumes the SAP PO Web API to send the results of a "movement" process identifier
When SAP PO Web API response is failed
Then system must retry until 6 times the information sending
And even sixth attempt is failed then update the status of the process identifier to failed
And store the system date time to have the sending traceability of the SAP PO response in SapTracking table
And the exception returned by SAP PO must be stored in application insights

@testcase=57646 @manual
Scenario: Verify failed submission of movement results to SAP PO and succeeded while retries
Given that the TRUE system consumes the SAP PO Web API to send the results of a "movement" process identifier
When SAP PO Web API response is failed
And system must retry until 6 times the information sending
And while retry the status of the process identifier is succeeded
Then update to send to SAP PO the process status in SapTracking table
And store the system date time to have the sending traceability of the SAP PO response in SapTracking table

@testcase=57647 @manual
Scenario: Verify the exceptions with error code when data to send the results of a process identifier to SAP PO
Given that the TRUE application is preparing the data to send the results of a process identifier to SAP PO
When the error description contains the error code
Then error code from description should be used to report the error code to SAP PO

@testcase=57648 @version=2 @bvt
Scenario: Verify the exceptions without error code when data to send the results of a inventory process identifier to SAP PO
Given that the TRUE system receives "Inventories" with errors through the Web API exposed to SAP PO
When the TRUE system finishes the inventories processing of a process identifier with error
And the error description does not contains the error code
Then generate a generic code and it should be used to report the error code to SAP PO

@testcase=57649 @version=2 @bvt
Scenario: Verify the exceptions without error code when data to send the results of a movement process identifier to SAP PO
Given that the TRUE system receives "Movements" with errors through the Web API exposed to SAP PO
When the TRUE system finishes the movements processing of a process identifier with error
And the error description does not contains the error code
Then generate a generic code and it should be used to report the error code to SAP PO

@testcase=66741 @bvt
Scenario: Verify invalid access token error should be shown when invalid token is passed while registration of movement through SapPo system
Given I have data to register "Movements" in system
When I have 1 movement with all mandatory attributes
And I register "Movements" in system with invalid token
Then the response should fail with "Unauthorized"

@testcase=66742 @bvt
Scenario: Verify invalid access token error should be shown when invalid token is passed while registration of inventory through SapPo system
Given I have data to register "Inventories" in system
When I have 1 inventories with all mandatory attributes
And I register "Inventories" in system with invalid token
Then the response should fail with "Unauthorized"